// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ReceiveError implements FrbException {
  final ReceiveErrorCode code;
  final String message;

  const ReceiveError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiveError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

/// Stable UI classification. Messages are display text, never a parsing protocol.
enum ReceiveErrorCode { gap, limit, stale, coverage, recovery, other }
