#!/usr/bin/env python3
"""Append new entries to the compiled-in mainnet block-time table.

The wallet estimates birthday heights and dates from this table instead of
asking lightwalletd about heights derived from the user's wallet. Entry `i` is
the header time of block `START_HEIGHT + i * STEP`.

The table is append-only. Each run fetches heights past the last entry, up to
`tip - REORG_MARGIN`, from two independent endpoints and requires them to
agree. It also re-reads the last existing entries and aborts if either
endpoint disagrees with the checked-in value. Nothing is written on any
failure.

Usage:
  scripts/update-mainnet-block-times.py            # fetch and append
  scripts/update-mainnet-block-times.py --check    # validate the file offline

Requires grpcurl. Exit status is 0 when the table is current or was updated,
and 1 on any failure.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import re
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "rust/src/wallet/block_times/mainnet_data.rs"
PROTO_DIR = REPO_ROOT / "protos"

START_HEIGHT = 419_200
STEP = 1_000
REORG_MARGIN = 1_000
RECHECK_EXISTING = 3
# Average spacing between consecutive entries must stay within these bounds.
# Mainnet targets 150 s before Blossom and 75 s after it.
MIN_AVG_BLOCK_SECONDS = 30
MAX_AVG_BLOCK_SECONDS = 300
DEFAULT_ENDPOINTS = ("zec.rocks:443", "eu.zec.stardust.rest:443")
RPC_TIMEOUT_SECONDS = 30
RPC_ATTEMPTS = 3
WORKERS = 8

HEADER = """\
// @generated by scripts/update-mainnet-block-times.py. Do not edit by hand.
//
// Header time of mainnet block `START_HEIGHT + i * STEP` for each entry `i`.
// A weekly workflow appends entries after two independent lightwalletd
// endpoints agree on each value.
"""

TIMES_PATTERN = re.compile(
    r"pub\(super\) const TIMES: &\[u32\] = &\[(?P<body>[^\]]*)\];", re.S
)
CONST_PATTERN = re.compile(r"pub\(super\) const (START_HEIGHT|STEP): u64 = ([0-9_]+);")


class UpdateError(Exception):
    pass


def read_table() -> list[int]:
    if not DATA_FILE.exists():
        return []
    text = DATA_FILE.read_text()
    consts = {name: int(value.replace("_", "")) for name, value in CONST_PATTERN.findall(text)}
    if consts != {"START_HEIGHT": START_HEIGHT, "STEP": STEP}:
        raise UpdateError(f"{DATA_FILE} has unexpected constants: {consts}")
    match = TIMES_PATTERN.search(text)
    if match is None:
        raise UpdateError(f"{DATA_FILE} has no TIMES array")
    return [int(token.replace("_", "")) for token in re.findall(r"[0-9_]+", match.group("body"))]


def render_table(times: list[int]) -> str:
    lines = [HEADER]
    lines.append(f"pub(super) const START_HEIGHT: u64 = {START_HEIGHT:_};")
    lines.append(f"pub(super) const STEP: u64 = {STEP:_};")
    lines.append("")
    lines.append("#[rustfmt::skip]")
    lines.append("pub(super) const TIMES: &[u32] = &[")
    for offset in range(0, len(times), 8):
        chunk = ", ".join(str(value) for value in times[offset : offset + 8])
        lines.append(f"    {chunk},")
    lines.append("];")
    return "\n".join(lines) + "\n"


def height_at(index: int) -> int:
    return START_HEIGHT + index * STEP


def validate(times: list[int], now: int) -> None:
    if not times:
        raise UpdateError("table is empty")
    for index in range(1, len(times)):
        previous, current = times[index - 1], times[index]
        if current < previous:
            raise UpdateError(
                f"time decreases at height {height_at(index)}: {previous} -> {current}"
            )
        average = (current - previous) / STEP
        if not MIN_AVG_BLOCK_SECONDS <= average <= MAX_AVG_BLOCK_SECONDS:
            raise UpdateError(
                f"average block interval {average:.1f}s before height {height_at(index)} "
                f"is outside {MIN_AVG_BLOCK_SECONDS}-{MAX_AVG_BLOCK_SECONDS}s"
            )
    if times[-1] > now:
        raise UpdateError(f"last entry {times[-1]} is in the future")


def grpc(endpoint: str, method: str, payload: dict) -> dict:
    command = [
        "grpcurl",
        "-max-time",
        str(RPC_TIMEOUT_SECONDS),
        "-import-path",
        str(PROTO_DIR),
        "-proto",
        "service.proto",
        "-d",
        json.dumps(payload),
        endpoint,
        f"cash.z.wallet.sdk.rpc.CompactTxStreamer/{method}",
    ]
    last_error = ""
    for attempt in range(RPC_ATTEMPTS):
        result = subprocess.run(command, capture_output=True, text=True)
        if result.returncode == 0:
            return json.loads(result.stdout)
        last_error = result.stderr.strip()
        time.sleep(2**attempt)
    raise UpdateError(f"{endpoint} {method} {payload}: {last_error}")


def tip_height(endpoint: str) -> int:
    return int(grpc(endpoint, "GetLatestBlock", {})["height"])


def block_time(endpoint: str, height: int) -> int:
    block = grpc(endpoint, "GetBlock", {"height": height})
    if int(block.get("height", -1)) != height:
        raise UpdateError(f"{endpoint} returned height {block.get('height')} for {height}")
    value = int(block.get("time", 0))
    if value <= 0:
        raise UpdateError(f"{endpoint} returned no time for height {height}")
    return value


def agreed_times(endpoints: tuple[str, str], indices: list[int]) -> dict[int, int]:
    """Fetch each index from both endpoints and require identical times."""
    jobs = [(endpoint, index) for index in indices for endpoint in endpoints]
    results: dict[tuple[str, int], int] = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=WORKERS) as pool:
        futures = {
            pool.submit(block_time, endpoint, height_at(index)): (endpoint, index)
            for endpoint, index in jobs
        }
        for future in concurrent.futures.as_completed(futures):
            results[futures[future]] = future.result()
    agreed = {}
    for index in indices:
        first, second = (results[(endpoint, index)] for endpoint in endpoints)
        if first != second:
            raise UpdateError(
                f"endpoints disagree at height {height_at(index)}: "
                f"{endpoints[0]}={first} {endpoints[1]}={second}"
            )
        agreed[index] = first
    return agreed


def update(endpoints: tuple[str, str]) -> None:
    times = read_table()
    if times:
        validate(times, int(time.time()))

    tips = [tip_height(endpoint) for endpoint in endpoints]
    safe_tip = min(tips) - REORG_MARGIN
    last_index = (safe_tip - START_HEIGHT) // STEP
    new_indices = list(range(len(times), last_index + 1))

    recheck = list(range(max(0, len(times) - RECHECK_EXISTING), len(times)))
    fetched = agreed_times(endpoints, recheck + new_indices)
    for index in recheck:
        if fetched[index] != times[index]:
            raise UpdateError(
                f"checked-in time at height {height_at(index)} is {times[index]}, "
                f"but both endpoints report {fetched[index]}"
            )

    if not new_indices:
        print(f"up to date: last height {height_at(len(times) - 1)}, tips {tips}")
        return

    updated = times + [fetched[index] for index in new_indices]
    validate(updated, int(time.time()))
    DATA_FILE.parent.mkdir(parents=True, exist_ok=True)
    DATA_FILE.write_text(render_table(updated))
    old_last = height_at(len(times) - 1) if times else None
    print(
        f"added {len(new_indices)} entries: last height {old_last} -> "
        f"{height_at(len(updated) - 1)} (agreed by {endpoints[0]} and {endpoints[1]})"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="validate the file without network access")
    parser.add_argument(
        "--endpoint",
        action="append",
        help="lightwalletd host:port; pass exactly twice to override the defaults",
    )
    args = parser.parse_args()
    try:
        if args.check:
            times = read_table()
            validate(times, int(time.time()))
            if DATA_FILE.read_text() != render_table(times):
                raise UpdateError(f"{DATA_FILE} is not in canonical generated form")
            print(f"ok: {len(times)} entries through height {height_at(len(times) - 1)}")
            return 0
        endpoints = tuple(args.endpoint or DEFAULT_ENDPOINTS)
        if len(endpoints) != 2 or endpoints[0] == endpoints[1]:
            raise UpdateError("exactly two distinct endpoints are required")
        update(endpoints)  # type: ignore[arg-type]
        return 0
    except UpdateError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
