#!/usr/bin/env python3
"""Append new entries to the compiled-in mainnet tree-state checkpoint table.

The wallet rounds restored birthdays down to these checkpoints and starts
scanning from the compiled tree state, so lightwalletd never sees a
`GetTreeState` request for the wallet's exact birthday. Entry `i` is
lightwalletd's `GetTreeState` reply for block `START_HEIGHT + i * STEP`.

The table is append-only. Each run fetches checkpoints past the last entry, up
to `tip - REORG_MARGIN`, from two independent endpoints and requires every
field to agree. It also re-reads the last existing entries and aborts if
either endpoint disagrees with the checked-in value. Nothing is written on any
failure.

Usage:
  scripts/update-mainnet-tree-states.py            # fetch and append
  scripts/update-mainnet-tree-states.py --check    # validate the file offline

Requires grpcurl. Exit status is 0 when the table is current or was updated,
and 1 on any failure.
"""

from __future__ import annotations

import argparse
import re
import sys
from typing import NamedTuple

from mainnet_tables import (
    RECHECK_EXISTING,
    REPO_ROOT,
    UpdateError,
    agreed,
    endpoints_from_args,
    grpc,
    safe_tip,
)

DATA_FILE = REPO_ROOT / "rust/src/wallet/tree_states/mainnet_data.rs"

START_HEIGHT = 420_000
STEP = 10_000
# Mainnet activation heights: a pool's tree must be empty before them.
NU5_ACTIVATION = 1_687_104
NU6_3_ACTIVATION = 3_428_143
TREE_DEPTH = 32

HEADER = """\
// @generated by scripts/update-mainnet-tree-states.py. Do not edit by hand.
//
// lightwalletd `GetTreeState` fields for mainnet block `START_HEIGHT + i * STEP`
// for each entry `i`. A weekly workflow appends entries after two independent
// lightwalletd endpoints agree on every field.

use super::Checkpoint;
"""

ENTRY_PATTERN = re.compile(
    r'Checkpoint \{ hash: "(?P<hash>[0-9a-f]*)", sapling: "(?P<sapling>[0-9a-f]*)", '
    r'orchard: "(?P<orchard>[0-9a-f]*)", ironwood: "(?P<ironwood>[0-9a-f]*)" \}'
)
CONST_PATTERN = re.compile(r"pub\(super\) const (START_HEIGHT|STEP): u64 = ([0-9_]+);")
HEX_HASH = re.compile(r"[0-9a-f]{64}")


class Checkpoint(NamedTuple):
    hash: str
    sapling: str
    orchard: str
    ironwood: str


def height_at(index: int) -> int:
    return START_HEIGHT + index * STEP


def read_table() -> list[Checkpoint]:
    if not DATA_FILE.exists():
        return []
    text = DATA_FILE.read_text()
    consts = {name: int(value.replace("_", "")) for name, value in CONST_PATTERN.findall(text)}
    if consts != {"START_HEIGHT": START_HEIGHT, "STEP": STEP}:
        raise UpdateError(f"{DATA_FILE} has unexpected constants: {consts}")
    return [Checkpoint(**match.groupdict()) for match in ENTRY_PATTERN.finditer(text)]


def render_table(checkpoints: list[Checkpoint]) -> str:
    lines = [HEADER]
    lines.append(f"pub(super) const START_HEIGHT: u64 = {START_HEIGHT:_};")
    lines.append(f"pub(super) const STEP: u64 = {STEP:_};")
    lines.append("")
    lines.append("#[rustfmt::skip]")
    lines.append("pub(super) const CHECKPOINTS: &[Checkpoint] = &[")
    for entry in checkpoints:
        lines.append(
            f'    Checkpoint {{ hash: "{entry.hash}", sapling: "{entry.sapling}", '
            f'orchard: "{entry.orchard}", ironwood: "{entry.ironwood}" }},'
        )
    lines.append("];")
    return "\n".join(lines) + "\n"


def tree_size(tree_hex: str) -> int:
    """Number of leaves in a legacy `CommitmentTree` encoding.

    The encoding is `Option<left> Option<right> CompactSize(n) Option<parent>*n`,
    where parent `k` summarizes `2^(k+1)` leaves.
    """
    if not tree_hex:
        return 0
    data = bytes.fromhex(tree_hex)
    offset = 0

    def read_option() -> bool:
        nonlocal offset
        if offset >= len(data):
            raise ValueError("truncated tree")
        flag = data[offset]
        offset += 1
        if flag == 0:
            return False
        if flag != 1 or offset + 32 > len(data):
            raise ValueError("bad optional node")
        offset += 32
        return True

    left = read_option()
    right = read_option()
    if offset >= len(data) or data[offset] >= 0xFD:
        raise ValueError("bad parent count")
    count = data[offset]
    offset += 1
    if count >= TREE_DEPTH:
        raise ValueError("too many parents")
    parents = [read_option() for _ in range(count)]
    if offset != len(data):
        raise ValueError("trailing bytes")
    if not left:
        if right or any(parents):
            raise ValueError("nodes without a left leaf")
        return 0
    return 1 + int(right) + sum(1 << (k + 1) for k, present in enumerate(parents) if present)


def validate(checkpoints: list[Checkpoint]) -> None:
    if not checkpoints:
        raise UpdateError("table is empty")
    previous = (0, 0, 0)
    for index, entry in enumerate(checkpoints):
        height = height_at(index)
        if not HEX_HASH.fullmatch(entry.hash) or entry.hash == "0" * 64:
            raise UpdateError(f"bad block hash at height {height}")
        if height < NU5_ACTIVATION and entry.orchard:
            raise UpdateError(f"Orchard tree before NU5 at height {height}")
        if height < NU6_3_ACTIVATION and entry.ironwood:
            raise UpdateError(f"Ironwood tree before NU6.3 at height {height}")
        try:
            sizes = tuple(
                tree_size(tree) for tree in (entry.sapling, entry.orchard, entry.ironwood)
            )
        except ValueError as error:
            raise UpdateError(f"unparseable tree at height {height}: {error}") from error
        if sizes[0] == 0:
            raise UpdateError(f"empty Sapling tree at height {height}")
        for pool, before, after in zip(("Sapling", "Orchard", "Ironwood"), previous, sizes):
            if after < before:
                raise UpdateError(f"{pool} tree shrinks at height {height}: {before} -> {after}")
        previous = sizes


def tree_state(endpoint: str, height: int) -> Checkpoint:
    reply = grpc(endpoint, "GetTreeState", {"height": height})
    if int(reply.get("height", -1)) != height:
        raise UpdateError(f"{endpoint} returned height {reply.get('height')} for {height}")
    if reply.get("network") != "main":
        raise UpdateError(f"{endpoint} returned network {reply.get('network')!r}")
    return Checkpoint(
        hash=reply.get("hash", "").lower(),
        sapling=reply.get("saplingTree", "").lower(),
        orchard=reply.get("orchardTree", "").lower(),
        ironwood=reply.get("ironwoodTree", "").lower(),
    )


def update(endpoints: tuple[str, str]) -> None:
    checkpoints = read_table()
    if checkpoints:
        validate(checkpoints)

    safe_height, tips = safe_tip(endpoints)
    last_index = (safe_height - START_HEIGHT) // STEP
    new_indices = list(range(len(checkpoints), last_index + 1))

    recheck = list(range(max(0, len(checkpoints) - RECHECK_EXISTING), len(checkpoints)))
    fetched = agreed(endpoints, [height_at(index) for index in recheck + new_indices], tree_state)
    for index in recheck:
        if fetched[height_at(index)] != checkpoints[index]:
            raise UpdateError(
                f"checked-in tree state at height {height_at(index)} differs from what "
                "both endpoints report"
            )

    if not new_indices:
        print(f"up to date: last height {height_at(len(checkpoints) - 1)}, tips {tips}")
        return

    updated = checkpoints + [fetched[height_at(index)] for index in new_indices]
    validate(updated)
    DATA_FILE.parent.mkdir(parents=True, exist_ok=True)
    DATA_FILE.write_text(render_table(updated))
    old_last = height_at(len(checkpoints) - 1) if checkpoints else None
    print(
        f"added {len(new_indices)} tree-state checkpoints: last height {old_last} -> "
        f"{height_at(len(updated) - 1)} (agreed by {endpoints[0]} and {endpoints[1]})"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="validate the file without network access")
    parser.add_argument(
        "--endpoint",
        action="append",
        help="lightwalletd host:port; pass exactly twice to override the defaults",
    )
    args = parser.parse_args()
    try:
        if args.check:
            checkpoints = read_table()
            validate(checkpoints)
            if DATA_FILE.read_text() != render_table(checkpoints):
                raise UpdateError(f"{DATA_FILE} is not in canonical generated form")
            print(
                f"ok: {len(checkpoints)} checkpoints through height "
                f"{height_at(len(checkpoints) - 1)}"
            )
            return 0
        update(endpoints_from_args(args.endpoint))
        return 0
    except UpdateError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
