// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

/// Reserves a swap address on a software account. `incoming` resumes the account's
/// draft or reserves the lowest eligible incoming index, after checking the swap
/// provider's seen set from the receiver directory (see `prepare_receive_reservation`);
/// its key scans from the next unscanned block until it closes. Otherwise it reserves
/// the next refund index, whose key starts scanning when the wallet stores the swap's
/// funding transaction. `live_tip` is the chain tip the quote flow fetched. Does not
/// start or restart ordinary wallet sync.
Future<SwapAddress> reserveSwapAddress({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required bool incoming,
  required BigInt liveTip,
}) => RustLib.instance.api.crateApiDynamicIvkReserveSwapAddress(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  incoming: incoming,
  liveTip: liveTip,
);

/// Persists an unknown outcome and scan watch just before a provider quote request
/// leaves the device, and returns the request's identity. `reservation_index` is the
/// incoming reservation [`reserve_swap_address`] returned, and `deadline_seconds` the
/// deposit deadline the request sends.
Future<String> beginReceiveQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required BigInt reservationIndex,
  required PlatformInt64 deadlineSeconds,
}) => RustLib.instance.api.crateApiDynamicIvkBeginReceiveQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  reservationIndex: reservationIndex,
  deadlineSeconds: deadlineSeconds,
);

/// Records how quote request `request_id` ended, even if the requesting UI has changed:
/// `accepted` with its deposit instructions, or, without them, definitively rejected,
/// which releases the request's hold on the address. Never call it for a timeout or a
/// malformed response.
Future<void> finishReceiveQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required String requestId,
  ReceiveDeposit? accepted,
}) => RustLib.instance.api.crateApiDynamicIvkFinishReceiveQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  requestId: requestId,
  accepted: accepted,
);

/// Locks the accepted quote's reservation before exposing provider funding
/// instructions, and returns the instructions to show.
Future<ReceiveDeposit> startReceiveQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required String requestId,
}) => RustLib.instance.api.crateApiDynamicIvkStartReceiveQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  requestId: requestId,
);

/// Binds an accepted refund quote's deposit address to the refund key reserved for
/// it, before the quote is shown. Funding requires this record.
Future<void> recordSwapRefundQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required BigInt refundIndex,
  required String depositAddress,
  required PlatformInt64 deadlineSeconds,
}) => RustLib.instance.api.crateApiDynamicIvkRecordSwapRefundQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  refundIndex: refundIndex,
  depositAddress: depositAddress,
  deadlineSeconds: deadlineSeconds,
);

/// Records a provider status, requested at `checked_at_seconds`, on the account's swap
/// operations with this deposit address and memo, and reclaims what that makes
/// reclaimable. `incoming` says the swap pays ZEC into the wallet; otherwise it is the
/// refund side of a ZEC deposit. `funded` says the provider saw a deposit. Swaps
/// without a private address are ignored. Do not call it for a failed status request.
Future<void> observeSwapStatus({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required bool incoming,
  required String depositAddress,
  String? depositMemo,
  required SwapProviderStatus status,
  required bool funded,
  required PlatformInt64 checkedAtSeconds,
}) => RustLib.instance.api.crateApiDynamicIvkObserveSwapStatus(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  incoming: incoming,
  depositAddress: depositAddress,
  depositMemo: depositMemo,
  status: status,
  funded: funded,
  checkedAtSeconds: checkedAtSeconds,
);

/// Queues one receiver-directory sweep of every closed swap key for the next sync,
/// which finds a second refund or a late payout that arrived after its key stopped
/// scanning. Called when the user turns NEAR swap privacy on.
Future<void> recheckSwapHistory({
  required String dbPath,
  required String networkName,
}) => RustLib.instance.api.crateApiDynamicIvkRecheckSwapHistory(
  dbPath: dbPath,
  networkName: networkName,
);

/// An incoming quote's deposit instructions, as the provider issued them.
class ReceiveDeposit {
  final String address;
  final String? memo;
  final PlatformInt64 deadlineSeconds;

  const ReceiveDeposit({
    required this.address,
    this.memo,
    required this.deadlineSeconds,
  });

  @override
  int get hashCode =>
      address.hashCode ^ memo.hashCode ^ deadlineSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiveDeposit &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          memo == other.memo &&
          deadlineSeconds == other.deadlineSeconds;
}

/// A private swap failure. `message` is display text, never a parsing protocol.
class ReceiveError implements FrbException {
  final String message;

  const ReceiveError({required this.message});

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiveError &&
          runtimeType == other.runtimeType &&
          message == other.message;
}

/// A durably reserved swap address. A refund address carries its refund key index; an
/// incoming one, its reservation's index.
class SwapAddress {
  final String address;
  final BigInt? refundIndex;
  final BigInt? reservationIndex;

  const SwapAddress({
    required this.address,
    this.refundIndex,
    this.reservationIndex,
  });

  @override
  int get hashCode =>
      address.hashCode ^ refundIndex.hashCode ^ reservationIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapAddress &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          refundIndex == other.refundIndex &&
          reservationIndex == other.reservationIndex;
}

/// The NEAR 1Click status fields that decide when a swap key stops scanning.
/// Amounts are base-unit decimal strings, as the provider reports them.
class SwapProviderStatus {
  final String status;
  final String? swapType;
  final String? refundedAmount;
  final String? amountOut;
  final PlatformInt64? deadlineSeconds;

  const SwapProviderStatus({
    required this.status,
    this.swapType,
    this.refundedAmount,
    this.amountOut,
    this.deadlineSeconds,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      swapType.hashCode ^
      refundedAmount.hashCode ^
      amountOut.hashCode ^
      deadlineSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapProviderStatus &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          swapType == other.swapType &&
          refundedAmount == other.refundedAmount &&
          amountOut == other.amountOut &&
          deadlineSeconds == other.deadlineSeconds;
}
