// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `expected_ledger_account`, `ledger_account_fingerprint`, `parse_ledger_db_network`, `require_mainnet`, `to_action_sigs`, `to_apdu_command`, `to_device_app`, `to_signed_operation`, `to_wallet_identity`

/// Read the application currently running on the connected Ledger device.
Future<LedgerDeviceApp> ledgerDeviceApp() =>
    RustLib.instance.api.crateApiLedgerLedgerDeviceApp();

/// Open the Zcash app when needed, reconnect, and verify it is running.
Future<LedgerDeviceApp> ledgerOpenZcashApp() =>
    RustLib.instance.api.crateApiLedgerLedgerOpenZcashApp();

/// Cancel the Ledger operation currently waiting for device interaction.
Future<void> ledgerCancelOperation() =>
    RustLib.instance.api.crateApiLedgerLedgerCancelOperation();

/// Export a Unified Full Viewing Key for `m/32'/133'/account'` after the user
/// approves the request on the Ledger device.
Future<String> ledgerExportUfvk({
  required int accountIndex,
  required String network,
}) => RustLib.instance.api.crateApiLedgerLedgerExportUfvk(
  accountIndex: accountIndex,
  network: network,
);

/// Export the UFVK and the stable derivation metadata Vizor needs to import
/// the corresponding watch-only account. The current Ledger APDU does not
/// expose the ZIP-32 seed fingerprint, so the PoC uses a domain-separated hash
/// of the approved UFVK as non-secret account metadata.
Future<LedgerAccountExport> ledgerExportAccount({
  required int accountIndex,
  required String network,
}) => RustLib.instance.api.crateApiLedgerLedgerExportAccount(
  accountIndex: accountIndex,
  network: network,
);

/// Read a stable wallet fingerprint without displaying an address or asking
/// for approval. When an account index is supplied, the response also carries
/// its first external transparent address for legacy-account verification.
Future<LedgerWalletIdentity> ledgerWalletIdentity({
  int? verificationAccountIndex,
  required String network,
}) => RustLib.instance.api.crateApiLedgerLedgerWalletIdentity(
  verificationAccountIndex: verificationAccountIndex,
  network: network,
);

/// Build the transport-neutral no-display public-key exchange used by BLE.
Future<LedgerWalletIdentityApduPlan> ledgerBuildWalletIdentityApduPlan({
  int? verificationAccountIndex,
}) => RustLib.instance.api.crateApiLedgerLedgerBuildWalletIdentityApduPlan(
  verificationAccountIndex: verificationAccountIndex,
);

/// Parse status-bearing BLE responses from the wallet-identity plan.
Future<LedgerWalletIdentity> ledgerParseMobileWalletIdentityResponses({
  int? verificationAccountIndex,
  required String network,
  required List<Uint8List> responses,
}) =>
    RustLib.instance.api.crateApiLedgerLedgerParseMobileWalletIdentityResponses(
      verificationAccountIndex: verificationAccountIndex,
      network: network,
      responses: responses,
    );

/// Derive the expected first external transparent address from an imported
/// account's stored UFVK. This is read-only and is used to enroll legacy
/// Ledger accounts into the wallet-identity grouping contract.
Future<String> ledgerAccountFirstTransparentAddress({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiLedgerLedgerAccountFirstTransparentAddress(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

/// Build the Zcash app's UFVK request without opening a desktop transport.
Future<LedgerUfvkApduPlan> ledgerBuildUfvkApduPlan({
  required int accountIndex,
}) => RustLib.instance.api.crateApiLedgerLedgerBuildUfvkApduPlan(
  accountIndex: accountIndex,
);

/// Parse status-bearing DMK responses, validate the UFVK using the existing
/// Zcash decoder, and produce the same import metadata as the macOS path.
Future<LedgerAccountExport> ledgerParseMobileUfvkResponses({
  required int accountIndex,
  required String network,
  required List<Uint8List> responses,
}) => RustLib.instance.api.crateApiLedgerLedgerParseMobileUfvkResponses(
  accountIndex: accountIndex,
  network: network,
  responses: responses,
);

/// Build the transport-neutral compact shielded PCZT signing exchange.
Future<LedgerPcztApduPlan> ledgerBuildPcztSigningApduPlan({
  required String dbPath,
  required String accountUuid,
  required List<int> pcztBytes,
  required String network,
}) => RustLib.instance.api.crateApiLedgerLedgerBuildPcztSigningApduPlan(
  dbPath: dbPath,
  accountUuid: accountUuid,
  pcztBytes: pcztBytes,
  network: network,
);

/// Build the transport-neutral full PCZT signing exchange.
Future<LedgerPcztApduPlan> ledgerBuildPcztFullSigningApduPlan({
  required String dbPath,
  required String accountUuid,
  required List<int> pcztBytes,
  required String network,
}) => RustLib.instance.api.crateApiLedgerLedgerBuildPcztFullSigningApduPlan(
  dbPath: dbPath,
  accountUuid: accountUuid,
  pcztBytes: pcztBytes,
  network: network,
);

/// Validate raw compact-signing responses and return shielded signatures.
Future<List<LedgerActionSig>> ledgerFinalizeMobilePcztSigning({
  required String dbPath,
  required String accountUuid,
  required List<int> pcztBytes,
  required String network,
  required List<Uint8List> responses,
}) => RustLib.instance.api.crateApiLedgerLedgerFinalizeMobilePcztSigning(
  dbPath: dbPath,
  accountUuid: accountUuid,
  pcztBytes: pcztBytes,
  network: network,
  responses: responses,
);

/// Validate raw full-signing responses and return the signed PCZT.
Future<Uint8List> ledgerFinalizeMobilePcztFullSigning({
  required String dbPath,
  required String accountUuid,
  required List<int> pcztBytes,
  required String network,
  required List<Uint8List> responses,
}) => RustLib.instance.api.crateApiLedgerLedgerFinalizeMobilePcztFullSigning(
  dbPath: dbPath,
  accountUuid: accountUuid,
  pcztBytes: pcztBytes,
  network: network,
  responses: responses,
);

/// Stream an Orchard/Ironwood PCZT into the Ledger app and return only the
/// spend authorization signatures after on-device review and approval.
Future<List<LedgerActionSig>> ledgerSignPczt({
  required String dbPath,
  required String accountUuid,
  required List<int> pcztBytes,
  required String network,
}) => RustLib.instance.api.crateApiLedgerLedgerSignPczt(
  dbPath: dbPath,
  accountUuid: accountUuid,
  pcztBytes: pcztBytes,
  network: network,
);

/// Stream a PCZT into Ledger, validate every returned transparent and
/// Orchard-family signature, and return the fully signed PCZT clone.
Future<Uint8List> ledgerSignPcztFull({
  required String dbPath,
  required String accountUuid,
  required List<int> pcztBytes,
  required String network,
}) => RustLib.instance.api.crateApiLedgerLedgerSignPcztFull(
  dbPath: dbPath,
  accountUuid: accountUuid,
  pcztBytes: pcztBytes,
  network: network,
);

/// Durably checkpoint a Ledger-signed PCZT pair before any broadcast attempt.
Future<LedgerSignedOperation> ledgerCheckpointSignedOperation({
  required String dbPath,
  required String network,
  required String operationId,
  required String accountUuid,
  required String kind,
  String? externalRef,
  required List<int> pcztWithProofsBytes,
  required List<int> pcztWithSignaturesBytes,
}) => RustLib.instance.api.crateApiLedgerLedgerCheckpointSignedOperation(
  dbPath: dbPath,
  network: network,
  operationId: operationId,
  accountUuid: accountUuid,
  kind: kind,
  externalRef: externalRef,
  pcztWithProofsBytes: pcztWithProofsBytes,
  pcztWithSignaturesBytes: pcztWithSignaturesBytes,
);

/// Durably checkpoint every proof/signature PCZT pair for one Ledger operation.
/// The complete batch is validated and committed as a single recoverable row.
Future<LedgerSignedOperation> ledgerCheckpointSignedOperationBatch({
  required String dbPath,
  required String network,
  required String operationId,
  required String accountUuid,
  required String kind,
  String? externalRef,
  required List<Uint8List> pcztWithProofs,
  required List<Uint8List> pcztWithSignatures,
}) => RustLib.instance.api.crateApiLedgerLedgerCheckpointSignedOperationBatch(
  dbPath: dbPath,
  network: network,
  operationId: operationId,
  accountUuid: accountUuid,
  kind: kind,
  externalRef: externalRef,
  pcztWithProofs: pcztWithProofs,
  pcztWithSignatures: pcztWithSignatures,
);

/// List checkpointed Ledger operations without exposing either PCZT blob.
Future<List<LedgerSignedOperation>> ledgerListSignedOperations({
  required String dbPath,
  required String network,
  String? accountUuid,
}) => RustLib.instance.api.crateApiLedgerLedgerListSignedOperations(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

/// Broadcast one checkpointed operation. Its signed bytes are loaded only in Rust.
Future<LedgerSignedOperationBroadcastResult> ledgerBroadcastSignedOperation({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String operationId,
  String? spendParamsPath,
  String? outputParamsPath,
}) => RustLib.instance.api.crateApiLedgerLedgerBroadcastSignedOperation(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  operationId: operationId,
  spendParamsPath: spendParamsPath,
  outputParamsPath: outputParamsPath,
);

/// Acknowledge and delete an operation whose broadcast result is pending.
Future<void> ledgerAckSignedOperation({
  required String dbPath,
  required String network,
  required String operationId,
}) => RustLib.instance.api.crateApiLedgerLedgerAckSignedOperation(
  dbPath: dbPath,
  network: network,
  operationId: operationId,
);

/// Public account material approved by the user on the Ledger device.
class LedgerAccountExport {
  final String ufvk;
  final Uint8List seedFingerprint;
  final int accountIndex;

  const LedgerAccountExport({
    required this.ufvk,
    required this.seedFingerprint,
    required this.accountIndex,
  });

  @override
  int get hashCode =>
      ufvk.hashCode ^ seedFingerprint.hashCode ^ accountIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerAccountExport &&
          runtimeType == other.runtimeType &&
          ufvk == other.ufvk &&
          seedFingerprint == other.seedFingerprint &&
          accountIndex == other.accountIndex;
}

/// A Ledger-produced spend authorization signature. `pool` is `0` for
/// Orchard and `1` for Ironwood; `sig` is always 64 bytes.
class LedgerActionSig {
  final int pool;
  final int actionIndex;
  final Uint8List sig;

  const LedgerActionSig({
    required this.pool,
    required this.actionIndex,
    required this.sig,
  });

  @override
  int get hashCode => pool.hashCode ^ actionIndex.hashCode ^ sig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerActionSig &&
          runtimeType == other.runtimeType &&
          pool == other.pool &&
          actionIndex == other.actionIndex &&
          sig == other.sig;
}

/// One transport-neutral APDU command. Mobile native code owns only the BLE
/// session and byte exchange; Rust remains the Zcash protocol authority.
class LedgerApduCommand {
  final int cla;
  final int ins;
  final int p1;
  final int p2;
  final Uint8List data;

  const LedgerApduCommand({
    required this.cla,
    required this.ins,
    required this.p1,
    required this.p2,
    required this.data,
  });

  @override
  int get hashCode =>
      cla.hashCode ^ ins.hashCode ^ p1.hashCode ^ p2.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerApduCommand &&
          runtimeType == other.runtimeType &&
          cla == other.cla &&
          ins == other.ins &&
          p1 == other.p1 &&
          p2 == other.p2 &&
          data == other.data;
}

/// The application currently running on the connected Ledger device.
class LedgerDeviceApp {
  final String appName;
  final String appVersion;

  const LedgerDeviceApp({required this.appName, required this.appVersion});

  @override
  int get hashCode => appName.hashCode ^ appVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerDeviceApp &&
          runtimeType == other.runtimeType &&
          appName == other.appName &&
          appVersion == other.appVersion;
}

/// Complete ordered APDU exchange for one PCZT signing operation.
class LedgerPcztApduPlan {
  final List<LedgerApduCommand> commands;

  const LedgerPcztApduPlan({required this.commands});

  @override
  int get hashCode => commands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerPcztApduPlan &&
          runtimeType == other.runtimeType &&
          commands == other.commands;
}

/// Durable Ledger operation metadata. Signed PCZT bytes never cross this API.
class LedgerSignedOperation {
  final String operationId;
  final String accountUuid;
  final String kind;
  final String? externalRef;
  final int? expiryHeight;
  final String state;
  final String? txid;
  final String? status;
  final String? message;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;

  const LedgerSignedOperation({
    required this.operationId,
    required this.accountUuid,
    required this.kind,
    this.externalRef,
    this.expiryHeight,
    required this.state,
    this.txid,
    this.status,
    this.message,
    required this.createdAtMs,
    required this.updatedAtMs,
  });

  @override
  int get hashCode =>
      operationId.hashCode ^
      accountUuid.hashCode ^
      kind.hashCode ^
      externalRef.hashCode ^
      expiryHeight.hashCode ^
      state.hashCode ^
      txid.hashCode ^
      status.hashCode ^
      message.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerSignedOperation &&
          runtimeType == other.runtimeType &&
          operationId == other.operationId &&
          accountUuid == other.accountUuid &&
          kind == other.kind &&
          externalRef == other.externalRef &&
          expiryHeight == other.expiryHeight &&
          state == other.state &&
          txid == other.txid &&
          status == other.status &&
          message == other.message &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs;
}

/// Result of broadcasting a checkpointed Ledger operation.
class LedgerSignedOperationBroadcastResult {
  final String operationId;
  final String txid;
  final String status;
  final String? message;
  final bool requiresAck;

  const LedgerSignedOperationBroadcastResult({
    required this.operationId,
    required this.txid,
    required this.status,
    this.message,
    required this.requiresAck,
  });

  @override
  int get hashCode =>
      operationId.hashCode ^
      txid.hashCode ^
      status.hashCode ^
      message.hashCode ^
      requiresAck.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerSignedOperationBroadcastResult &&
          runtimeType == other.runtimeType &&
          operationId == other.operationId &&
          txid == other.txid &&
          status == other.status &&
          message == other.message &&
          requiresAck == other.requiresAck;
}

class LedgerUfvkApduPlan {
  final LedgerApduCommand first;
  final LedgerApduCommand continuation;

  const LedgerUfvkApduPlan({required this.first, required this.continuation});

  @override
  int get hashCode => first.hashCode ^ continuation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerUfvkApduPlan &&
          runtimeType == other.runtimeType &&
          first == other.first &&
          continuation == other.continuation;
}

/// Public, non-spending identity material used only to group local Ledger
/// accounts that come from the same seed.
class LedgerWalletIdentity {
  final String fingerprint;
  final String? verificationAddress;

  const LedgerWalletIdentity({
    required this.fingerprint,
    this.verificationAddress,
  });

  @override
  int get hashCode => fingerprint.hashCode ^ verificationAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerWalletIdentity &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          verificationAddress == other.verificationAddress;
}

class LedgerWalletIdentityApduPlan {
  final List<LedgerApduCommand> commands;

  const LedgerWalletIdentityApduPlan({required this.commands});

  @override
  int get hashCode => commands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerWalletIdentityApduPlan &&
          runtimeType == other.runtimeType &&
          commands == other.commands;
}
