// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `expected_ledger_account`, `ledger_account_fingerprint`, `parse_ledger_db_network`, `require_account_index`, `require_mainnet`, `to_action_sigs`, `to_apdu_command`, `to_device_app`, `validate_ufvk`

/// Read the application currently running on the connected Ledger device.
Future<LedgerDeviceApp> ledgerDeviceApp() =>
    RustLib.instance.api.crateApiLedgerLedgerDeviceApp();

/// Open the Zcash app when needed, reconnect, and verify it is running.
Future<LedgerDeviceApp> ledgerOpenZcashApp() =>
    RustLib.instance.api.crateApiLedgerLedgerOpenZcashApp();

/// Cancel the Ledger operation currently waiting for device interaction.
/// Runs on the caller's FFI invocation so busy device workers cannot delay it.
void ledgerCancelOperation() =>
    RustLib.instance.api.crateApiLedgerLedgerCancelOperation();

/// Export an account's UFVK and derivation metadata after device approval.
/// The Ledger app does not export the ZIP-32 seed fingerprint. The synthetic
/// hash here fills the DB derivation slot; it cannot identify a seed or device.
Future<LedgerAccountExport> ledgerExportAccount({
  required int accountIndex,
  required String network,
}) => RustLib.instance.api.crateApiLedgerLedgerExportAccount(
  accountIndex: accountIndex,
  network: network,
);

/// Build the Zcash app's UFVK request without opening a desktop transport.
Future<LedgerUfvkApduPlan> ledgerBuildUfvkApduPlan({
  required int accountIndex,
}) => RustLib.instance.api.crateApiLedgerLedgerBuildUfvkApduPlan(
  accountIndex: accountIndex,
);

/// Parse status-bearing Bluetooth responses and produce the same public
/// account metadata as the USB export path.
Future<LedgerAccountExport> ledgerParseMobileUfvkResponses({
  required int accountIndex,
  required String network,
  required List<Uint8List> responses,
}) => RustLib.instance.api.crateApiLedgerLedgerParseMobileUfvkResponses(
  accountIndex: accountIndex,
  network: network,
  responses: responses,
);

/// Build the transport-neutral compact shielded PCZT signing exchange.
Future<LedgerPcztApduPlan> ledgerBuildPcztSigningApduPlan({
  required String dbPath,
  required String accountUuid,
  required List<int> pcztBytes,
  required String network,
}) => RustLib.instance.api.crateApiLedgerLedgerBuildPcztSigningApduPlan(
  dbPath: dbPath,
  accountUuid: accountUuid,
  pcztBytes: pcztBytes,
  network: network,
);

/// Build the transport-neutral full PCZT signing exchange.
Future<LedgerPcztApduPlan> ledgerBuildPcztFullSigningApduPlan({
  required String dbPath,
  required String accountUuid,
  required List<int> pcztBytes,
  required String network,
}) => RustLib.instance.api.crateApiLedgerLedgerBuildPcztFullSigningApduPlan(
  dbPath: dbPath,
  accountUuid: accountUuid,
  pcztBytes: pcztBytes,
  network: network,
);

/// Validate raw compact-signing responses and return shielded signatures.
Future<List<LedgerActionSig>> ledgerFinalizeMobilePcztSigning({
  required String dbPath,
  required String accountUuid,
  required List<int> pcztBytes,
  required String network,
  required List<Uint8List> responses,
}) => RustLib.instance.api.crateApiLedgerLedgerFinalizeMobilePcztSigning(
  dbPath: dbPath,
  accountUuid: accountUuid,
  pcztBytes: pcztBytes,
  network: network,
  responses: responses,
);

/// Validate raw full-signing responses and return the signed PCZT.
Future<Uint8List> ledgerFinalizeMobilePcztFullSigning({
  required String dbPath,
  required String accountUuid,
  required List<int> pcztBytes,
  required String network,
  required List<Uint8List> responses,
}) => RustLib.instance.api.crateApiLedgerLedgerFinalizeMobilePcztFullSigning(
  dbPath: dbPath,
  accountUuid: accountUuid,
  pcztBytes: pcztBytes,
  network: network,
  responses: responses,
);

/// Reject a PCZT shape that the supported Ledger app cannot sign safely.
Future<void> ledgerValidateSupportedPczt({required List<int> pcztBytes}) =>
    RustLib.instance.api.crateApiLedgerLedgerValidateSupportedPczt(
      pcztBytes: pcztBytes,
    );

/// Stream a shielded PCZT into Ledger and return spend authorization signatures.
Future<List<LedgerActionSig>> ledgerSignPczt({
  required String dbPath,
  required String accountUuid,
  required List<int> pcztBytes,
  required String network,
}) => RustLib.instance.api.crateApiLedgerLedgerSignPczt(
  dbPath: dbPath,
  accountUuid: accountUuid,
  pcztBytes: pcztBytes,
  network: network,
);

/// Stream one PCZT into Ledger and return a fully verified signed clone.
Future<Uint8List> ledgerSignPcztFull({
  required String dbPath,
  required String accountUuid,
  required List<int> pcztBytes,
  required String network,
}) => RustLib.instance.api.crateApiLedgerLedgerSignPcztFull(
  dbPath: dbPath,
  accountUuid: accountUuid,
  pcztBytes: pcztBytes,
  network: network,
);

/// Viewing-key material for one approved Ledger account; never a spending key.
class LedgerAccountExport {
  final String ufvk;

  /// Synthetic account-scoped DB metadata, not the real ZIP-32 seed fingerprint.
  final Uint8List seedFingerprint;
  final int accountIndex;

  /// USB product name, for display only; not a device identity.
  final String? deviceModel;

  const LedgerAccountExport({
    required this.ufvk,
    required this.seedFingerprint,
    required this.accountIndex,
    this.deviceModel,
  });

  @override
  int get hashCode =>
      ufvk.hashCode ^
      seedFingerprint.hashCode ^
      accountIndex.hashCode ^
      deviceModel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerAccountExport &&
          runtimeType == other.runtimeType &&
          ufvk == other.ufvk &&
          seedFingerprint == other.seedFingerprint &&
          accountIndex == other.accountIndex &&
          deviceModel == other.deviceModel;
}

/// A Ledger-produced spend authorization signature. `pool` is `0` for
/// Orchard and `1` for Ironwood; `sig` is always 64 bytes.
class LedgerActionSig {
  final int pool;
  final int actionIndex;
  final Uint8List sig;

  const LedgerActionSig({
    required this.pool,
    required this.actionIndex,
    required this.sig,
  });

  @override
  int get hashCode => pool.hashCode ^ actionIndex.hashCode ^ sig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerActionSig &&
          runtimeType == other.runtimeType &&
          pool == other.pool &&
          actionIndex == other.actionIndex &&
          sig == other.sig;
}

/// One transport-neutral APDU command. Native Bluetooth adapters own only the
/// session and byte exchange; Rust remains the Zcash protocol authority.
class LedgerApduCommand {
  final int cla;
  final int ins;
  final int p1;
  final int p2;
  final Uint8List data;

  const LedgerApduCommand({
    required this.cla,
    required this.ins,
    required this.p1,
    required this.p2,
    required this.data,
  });

  @override
  int get hashCode =>
      cla.hashCode ^ ins.hashCode ^ p1.hashCode ^ p2.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerApduCommand &&
          runtimeType == other.runtimeType &&
          cla == other.cla &&
          ins == other.ins &&
          p1 == other.p1 &&
          p2 == other.p2 &&
          data == other.data;
}

/// The application currently running on the connected Ledger device.
class LedgerDeviceApp {
  final String appName;
  final String appVersion;

  const LedgerDeviceApp({required this.appName, required this.appVersion});

  @override
  int get hashCode => appName.hashCode ^ appVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerDeviceApp &&
          runtimeType == other.runtimeType &&
          appName == other.appName &&
          appVersion == other.appVersion;
}

/// Complete ordered APDU exchange for one PCZT signing operation.
class LedgerPcztApduPlan {
  final List<LedgerApduCommand> commands;

  const LedgerPcztApduPlan({required this.commands});

  @override
  int get hashCode => commands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerPcztApduPlan &&
          runtimeType == other.runtimeType &&
          commands == other.commands;
}

/// The first UFVK request and its continuation command.
class LedgerUfvkApduPlan {
  final LedgerApduCommand first;
  final LedgerApduCommand continuation;

  const LedgerUfvkApduPlan({required this.first, required this.continuation});

  @override
  int get hashCode => first.hashCode ^ continuation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerUfvkApduPlan &&
          runtimeType == other.runtimeType &&
          first == other.first &&
          continuation == other.continuation;
}
