// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `require_mainnet`, `to_device_app`

/// Read the application currently running on the connected Ledger device.
Future<LedgerDeviceApp> ledgerDeviceApp() =>
    RustLib.instance.api.crateApiLedgerLedgerDeviceApp();

/// Open the Zcash app when needed, reconnect, and verify it is running.
Future<LedgerDeviceApp> ledgerOpenZcashApp() =>
    RustLib.instance.api.crateApiLedgerLedgerOpenZcashApp();

/// Cancel the Ledger operation currently waiting for device interaction.
/// Runs on the caller's FFI invocation so busy device workers cannot delay it.
void ledgerCancelOperation() =>
    RustLib.instance.api.crateApiLedgerLedgerCancelOperation();

/// Export the UFVK for the selected mainnet account after device approval.
///
/// The request includes the shielded `m/32'/133'/account'` and transparent
/// `m/44'/133'/account'` derivation paths. This does not import an account into
/// the wallet or return seed/spending keys.
Future<String> ledgerExportUfvk({
  required int accountIndex,
  required String network,
}) => RustLib.instance.api.crateApiLedgerLedgerExportUfvk(
  accountIndex: accountIndex,
  network: network,
);

/// The application currently running on the connected Ledger device.
class LedgerDeviceApp {
  final String appName;
  final String appVersion;

  const LedgerDeviceApp({required this.appName, required this.appVersion});

  @override
  int get hashCode => appName.hashCode ^ appVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerDeviceApp &&
          runtimeType == other.runtimeType &&
          appName == other.appName &&
          appVersion == other.appVersion;
}
