// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `multisig_identity_from_keys`, `normalize_backup_passphrase`, `random_word_index`

ApiMultisigThresholdParams validateMultisigThreshold({
  required int threshold,
  required int participantCount,
}) => RustLib.instance.api.crateApiMultisigValidateMultisigThreshold(
  threshold: threshold,
  participantCount: participantCount,
);

ApiMultisigParticipantIdentity generateMultisigParticipantIdentity() =>
    RustLib.instance.api.crateApiMultisigGenerateMultisigParticipantIdentity();

ApiMultisigParticipantIdentity restoreMultisigParticipantIdentity({
  required String admissionSecretKey,
  required String deliverySecretKey,
}) => RustLib.instance.api.crateApiMultisigRestoreMultisigParticipantIdentity(
  admissionSecretKey: admissionSecretKey,
  deliverySecretKey: deliverySecretKey,
);

ApiMultisigBackupPassword generateMultisigBackupPassword() =>
    RustLib.instance.api.crateApiMultisigGenerateMultisigBackupPassword();

String normalizeMultisigBackupPassword({
  required String password,
  required bool generated,
}) => RustLib.instance.api.crateApiMultisigNormalizeMultisigBackupPassword(
  password: password,
  generated: generated,
);

class ApiMultisigBackupPassword {
  final String displayPassword;
  final String canonicalPassword;
  final String checksum;

  const ApiMultisigBackupPassword({
    required this.displayPassword,
    required this.canonicalPassword,
    required this.checksum,
  });

  @override
  int get hashCode =>
      displayPassword.hashCode ^ canonicalPassword.hashCode ^ checksum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigBackupPassword &&
          runtimeType == other.runtimeType &&
          displayPassword == other.displayPassword &&
          canonicalPassword == other.canonicalPassword &&
          checksum == other.checksum;
}

class ApiMultisigParticipantIdentity {
  final String admissionSecretKey;
  final String admissionPublicKey;
  final String deliverySecretKey;
  final String deliveryPublicKey;

  const ApiMultisigParticipantIdentity({
    required this.admissionSecretKey,
    required this.admissionPublicKey,
    required this.deliverySecretKey,
    required this.deliveryPublicKey,
  });

  @override
  int get hashCode =>
      admissionSecretKey.hashCode ^
      admissionPublicKey.hashCode ^
      deliverySecretKey.hashCode ^
      deliveryPublicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigParticipantIdentity &&
          runtimeType == other.runtimeType &&
          admissionSecretKey == other.admissionSecretKey &&
          admissionPublicKey == other.admissionPublicKey &&
          deliverySecretKey == other.deliverySecretKey &&
          deliveryPublicKey == other.deliveryPublicKey;
}

class ApiMultisigThresholdParams {
  final int threshold;
  final int participantCount;

  const ApiMultisigThresholdParams({
    required this.threshold,
    required this.participantCount,
  });

  @override
  int get hashCode => threshold.hashCode ^ participantCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigThresholdParams &&
          runtimeType == other.runtimeType &&
          threshold == other.threshold &&
          participantCount == other.participantCount;
}
