// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `all_dkg_round1_packages`, `all_sent_to`, `block_on`, `classify_client_status`, `clean_label`, `client_error`, `collect_signing_inbox`, `create_progress_with`, `decode_b64_32`, `decode_b64`, `decrypt_create_message`, `decrypt_signing_message`, `dkg_identifier`, `ensure_auth_owner`, `ensure_dkg_finalized`, `ensure_dkg_round1`, `ensure_dkg_round2`, `ensure_round1_ready`, `ensure_round2_ready`, `ensure_selected_signer`, `hash_bytes_b64`, `hash_group_public_package`, `idempotency_key`, `identifier_from_hex`, `insert_unique_round1`, `insert_unique_round2`, `map_auth_session`, `map_auth_update_from_session`, `map_auth_update_from_tokens`, `map_participant`, `map_session`, `map_signing_request`, `map_tokens`, `mark_sent_to`, `missing_round1_participants`, `missing_round2_participants`, `multisig_identity_from_keys`, `new`, `new`, `normalize_backup_passphrase`, `normalize_selected_participants`, `own_roster_entry`, `parse_create_state`, `parse_key_package_b64`, `parse_signing_state`, `poll_create_inbox`, `post_create_message_with_outbox`, `post_signing_body_to_selected`, `prepare_multisig_signing_request_inner`, `random_word_index`, `refresh_error_allows_resume`, `restore_participant_identity`, `resume_participant_auth_session`, `roster_entry`, `round1_commitments_for_action`, `round2_shares_for_action`, `round_action_msg`, `seal_label`, `seed_issuer_participant_id`, `sent_to_contains`, `session_recipients`, `session_state_phase`, `signing_advance_with_submission`, `signing_advance`, `signing_recipients`, `stable_hash`, `stable_id`, `state_action_indices`, `status_code_allows_resume`, `structured_multisig_error`, `sync_locked_roster`, `unix_now_secs`, `unsigned_orchard_action_indices`, `vault_address_from_group_public_package`, `without_identifier`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ApiMultisigErrorBody`, `ApiMultisigErrorKind`, `LocalCreateState`, `LocalRosterParticipant`, `LocalSigningState`, `SigningInboxMessages`, `TxRequestBody`, `TxRound1Body`, `TxRound2Body`, `TxRoundActionMsg`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

ApiMultisigThresholdParams validateMultisigThreshold({
  required int threshold,
  required int participantCount,
}) => RustLib.instance.api.crateApiMultisigValidateMultisigThreshold(
  threshold: threshold,
  participantCount: participantCount,
);

/// Random 32-byte session invite secret (base64url). Shared out-of-band as
/// part of the invite code; never sent to the coordinator. Participant
/// labels are sealed under it so the server only relays opaque strings.
String generateMultisigInviteSecret() =>
    RustLib.instance.api.crateApiMultisigGenerateMultisigInviteSecret();

ApiMultisigParticipantIdentity generateMultisigParticipantIdentity() =>
    RustLib.instance.api.crateApiMultisigGenerateMultisigParticipantIdentity();

ApiMultisigParticipantIdentity restoreMultisigParticipantIdentity({
  required String admissionSecretKey,
  required String deliverySecretKey,
}) => RustLib.instance.api.crateApiMultisigRestoreMultisigParticipantIdentity(
  admissionSecretKey: admissionSecretKey,
  deliverySecretKey: deliverySecretKey,
);

ApiMultisigBackupPassword generateMultisigBackupPassword() =>
    RustLib.instance.api.crateApiMultisigGenerateMultisigBackupPassword();

String normalizeMultisigBackupPassword({
  required String password,
  required bool generated,
}) => RustLib.instance.api.crateApiMultisigNormalizeMultisigBackupPassword(
  password: password,
  generated: generated,
);

Future<ApiMultisigBackupArtifact> createMultisigShareBackup({
  required String network,
  required String sessionId,
  required String participantId,
  required int threshold,
  required int participantCount,
  required String rosterHash,
  required String admissionSecretKey,
  required String deliverySecretKey,
  required String keyPackageB64,
  required String groupPublicPackageJson,
  required String passphrase,
}) => RustLib.instance.api.crateApiMultisigCreateMultisigShareBackup(
  network: network,
  sessionId: sessionId,
  participantId: participantId,
  threshold: threshold,
  participantCount: participantCount,
  rosterHash: rosterHash,
  admissionSecretKey: admissionSecretKey,
  deliverySecretKey: deliverySecretKey,
  keyPackageB64: keyPackageB64,
  groupPublicPackageJson: groupPublicPackageJson,
  passphrase: passphrase,
);

Future<ApiMultisigBackupVerification> verifyMultisigShareBackup({
  required String network,
  required String artifactJson,
  required String passphrase,
  required String expectedSessionId,
  required String expectedParticipantId,
  required int expectedThreshold,
  required int expectedParticipantCount,
  required String expectedRosterHash,
  required String expectedGroupPublicPackageHash,
}) => RustLib.instance.api.crateApiMultisigVerifyMultisigShareBackup(
  network: network,
  artifactJson: artifactJson,
  passphrase: passphrase,
  expectedSessionId: expectedSessionId,
  expectedParticipantId: expectedParticipantId,
  expectedThreshold: expectedThreshold,
  expectedParticipantCount: expectedParticipantCount,
  expectedRosterHash: expectedRosterHash,
  expectedGroupPublicPackageHash: expectedGroupPublicPackageHash,
);

Future<ApiMultisigAuthSession> createMultisigSession({
  required String coordinatorUrl,
  required String admissionSecretKey,
  required String deliverySecretKey,
  required String inviteSecret,
  String? label,
}) => RustLib.instance.api.crateApiMultisigCreateMultisigSession(
  coordinatorUrl: coordinatorUrl,
  admissionSecretKey: admissionSecretKey,
  deliverySecretKey: deliverySecretKey,
  inviteSecret: inviteSecret,
  label: label,
);

Future<ApiMultisigAuthSession> joinMultisigSession({
  required String coordinatorUrl,
  required String sessionId,
  required String admissionSecretKey,
  required String deliverySecretKey,
  required String inviteSecret,
  String? label,
}) => RustLib.instance.api.crateApiMultisigJoinMultisigSession(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  admissionSecretKey: admissionSecretKey,
  deliverySecretKey: deliverySecretKey,
  inviteSecret: inviteSecret,
  label: label,
);

Future<ApiMultisigTokens> refreshMultisigAuth({
  required String coordinatorUrl,
  required String refreshToken,
}) => RustLib.instance.api.crateApiMultisigRefreshMultisigAuth(
  coordinatorUrl: coordinatorUrl,
  refreshToken: refreshToken,
);

Future<ApiMultisigAuthUpdate> refreshOrResumeMultisigAuth({
  required String coordinatorUrl,
  required String sessionId,
  required String participantId,
  required String refreshToken,
  required String admissionSecretKey,
  required String deliverySecretKey,
}) => RustLib.instance.api.crateApiMultisigRefreshOrResumeMultisigAuth(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  participantId: participantId,
  refreshToken: refreshToken,
  admissionSecretKey: admissionSecretKey,
  deliverySecretKey: deliverySecretKey,
);

Future<ApiMultisigAuthSession> resumeMultisigParticipant({
  required String coordinatorUrl,
  required String sessionId,
  required String admissionSecretKey,
  required String deliverySecretKey,
  String? inviteSecret,
}) => RustLib.instance.api.crateApiMultisigResumeMultisigParticipant(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  admissionSecretKey: admissionSecretKey,
  deliverySecretKey: deliverySecretKey,
  inviteSecret: inviteSecret,
);

Future<ApiMultisigSession> getMultisigSession({
  required String coordinatorUrl,
  required String sessionId,
  required String accessToken,
  String? inviteSecret,
}) => RustLib.instance.api.crateApiMultisigGetMultisigSession(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  accessToken: accessToken,
  inviteSecret: inviteSecret,
);

Future<ApiMultisigSession> lockMultisigSession({
  required String coordinatorUrl,
  required String sessionId,
  required String accessToken,
  required int threshold,
  String? inviteSecret,
}) => RustLib.instance.api.crateApiMultisigLockMultisigSession(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  accessToken: accessToken,
  threshold: threshold,
  inviteSecret: inviteSecret,
);

Future<ApiMultisigCreateAdvance> advanceMultisigCreate({
  required String coordinatorUrl,
  required String sessionId,
  required String participantId,
  required String accessToken,
  required String admissionSecretKey,
  required String deliverySecretKey,
  String? inviteSecret,
  String? localStateJson,
}) => RustLib.instance.api.crateApiMultisigAdvanceMultisigCreate(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  participantId: participantId,
  accessToken: accessToken,
  admissionSecretKey: admissionSecretKey,
  deliverySecretKey: deliverySecretKey,
  inviteSecret: inviteSecret,
  localStateJson: localStateJson,
);

Future<ApiPreparedMultisigSigningRequest> prepareMultisigSigningRequest({
  required String coordinatorUrl,
  required String sessionId,
  required String participantId,
  required String accessToken,
  required String rosterHash,
  required String requestSeed,
  required List<String> selectedParticipantIds,
  required List<int> pcztBytes,
  required bool needsSaplingParams,
  required String amountZatoshi,
  required String feeZatoshi,
  required String recipientAddress,
  String? memo,
}) => RustLib.instance.api.crateApiMultisigPrepareMultisigSigningRequest(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  participantId: participantId,
  accessToken: accessToken,
  rosterHash: rosterHash,
  requestSeed: requestSeed,
  selectedParticipantIds: selectedParticipantIds,
  pcztBytes: pcztBytes,
  needsSaplingParams: needsSaplingParams,
  amountZatoshi: amountZatoshi,
  feeZatoshi: feeZatoshi,
  recipientAddress: recipientAddress,
  memo: memo,
);

Future<ApiMultisigSigningRequest> submitPreparedMultisigSigningRequest({
  required String coordinatorUrl,
  required String sessionId,
  required String accessToken,
  required String pcztHash,
  required String requestJson,
  required String idempotencyKey,
}) => RustLib.instance.api.crateApiMultisigSubmitPreparedMultisigSigningRequest(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  accessToken: accessToken,
  pcztHash: pcztHash,
  requestJson: requestJson,
  idempotencyKey: idempotencyKey,
);

/// Publishes the local participant's label for the finalized vault as a
/// broadcast message encrypted to the group-derived metadata keypair. The
/// coordinator relays ciphertext only. Safe to call repeatedly: the
/// idempotency key is stable and a same-key replay (or the 409 produced by
/// a re-encrypted retry) counts as already published.
Future<void> postMultisigVaultLabel({
  required String coordinatorUrl,
  required String sessionId,
  required String participantId,
  required String accessToken,
  required String rosterHash,
  required String groupPublicPackageJson,
  required String label,
}) => RustLib.instance.api.crateApiMultisigPostMultisigVaultLabel(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  participantId: participantId,
  accessToken: accessToken,
  rosterHash: rosterHash,
  groupPublicPackageJson: groupPublicPackageJson,
  label: label,
);

Future<ApiMultisigSigningRequest> getMultisigSigningRequest({
  required String coordinatorUrl,
  required String signingRequestId,
  required String accessToken,
  required String pcztHash,
}) => RustLib.instance.api.crateApiMultisigGetMultisigSigningRequest(
  coordinatorUrl: coordinatorUrl,
  signingRequestId: signingRequestId,
  accessToken: accessToken,
  pcztHash: pcztHash,
);

Future<ApiMultisigSigningInbox> getMultisigSigningInbox({
  required String coordinatorUrl,
  required String sessionId,
  required String participantId,
  required String accessToken,
  required String rosterHash,
  required String deliverySecretKey,
  String? groupPublicPackageJson,
  required PlatformInt64 after,
}) => RustLib.instance.api.crateApiMultisigGetMultisigSigningInbox(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  participantId: participantId,
  accessToken: accessToken,
  rosterHash: rosterHash,
  deliverySecretKey: deliverySecretKey,
  groupPublicPackageJson: groupPublicPackageJson,
  after: after,
);

Future<ApiMultisigSessionEvents> getMultisigSessionEvents({
  required String coordinatorUrl,
  required String sessionId,
  required String accessToken,
  required PlatformInt64 after,
}) => RustLib.instance.api.crateApiMultisigGetMultisigSessionEvents(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  accessToken: accessToken,
  after: after,
);

Future<ApiMultisigSigningAdvance> submitMultisigSigningRound1({
  required String coordinatorUrl,
  required String sessionId,
  required String signingRequestId,
  required String participantId,
  required String accessToken,
  required String rosterHash,
  required List<String> selectedParticipantIds,
  required List<int> pcztBytes,
  required String keyPackageB64,
  String? localStateJson,
}) => RustLib.instance.api.crateApiMultisigSubmitMultisigSigningRound1(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  signingRequestId: signingRequestId,
  participantId: participantId,
  accessToken: accessToken,
  rosterHash: rosterHash,
  selectedParticipantIds: selectedParticipantIds,
  pcztBytes: pcztBytes,
  keyPackageB64: keyPackageB64,
  localStateJson: localStateJson,
);

Future<ApiMultisigSigningAdvance> submitMultisigSigningRound2({
  required String coordinatorUrl,
  required String sessionId,
  required String signingRequestId,
  required String participantId,
  required String accessToken,
  required String rosterHash,
  required String deliverySecretKey,
  required List<String> selectedParticipantIds,
  required List<int> pcztBytes,
  required String keyPackageB64,
  String? localStateJson,
}) => RustLib.instance.api.crateApiMultisigSubmitMultisigSigningRound2(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  signingRequestId: signingRequestId,
  participantId: participantId,
  accessToken: accessToken,
  rosterHash: rosterHash,
  deliverySecretKey: deliverySecretKey,
  selectedParticipantIds: selectedParticipantIds,
  pcztBytes: pcztBytes,
  keyPackageB64: keyPackageB64,
  localStateJson: localStateJson,
);

Future<ApiMultisigSignedPczt> aggregateMultisigSignedPczt({
  required String coordinatorUrl,
  required String sessionId,
  required String signingRequestId,
  required String participantId,
  required String accessToken,
  required String rosterHash,
  required String deliverySecretKey,
  required List<String> selectedParticipantIds,
  required List<int> pcztBytes,
  required String groupPublicPackageJson,
  String? localStateJson,
}) => RustLib.instance.api.crateApiMultisigAggregateMultisigSignedPczt(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  signingRequestId: signingRequestId,
  participantId: participantId,
  accessToken: accessToken,
  rosterHash: rosterHash,
  deliverySecretKey: deliverySecretKey,
  selectedParticipantIds: selectedParticipantIds,
  pcztBytes: pcztBytes,
  groupPublicPackageJson: groupPublicPackageJson,
  localStateJson: localStateJson,
);

Future<ApiMultisigSigningAdvance> postMultisigBroadcastResult({
  required String coordinatorUrl,
  required String sessionId,
  required String signingRequestId,
  required String participantId,
  required String accessToken,
  required String rosterHash,
  required List<String> selectedParticipantIds,
  required String pcztHash,
  required String txid,
  String? localStateJson,
}) => RustLib.instance.api.crateApiMultisigPostMultisigBroadcastResult(
  coordinatorUrl: coordinatorUrl,
  sessionId: sessionId,
  signingRequestId: signingRequestId,
  participantId: participantId,
  accessToken: accessToken,
  rosterHash: rosterHash,
  selectedParticipantIds: selectedParticipantIds,
  pcztHash: pcztHash,
  txid: txid,
  localStateJson: localStateJson,
);

class ApiMultisigAuthSession {
  final String sessionId;
  final String participantId;
  final String accessToken;
  final String refreshToken;
  final String admissionSecretKey;
  final String admissionPublicKey;
  final String deliverySecretKey;
  final String deliveryPublicKey;
  final BigInt accessTokenExpiresAt;
  final BigInt refreshTokenExpiresAt;
  final String state;
  final ApiMultisigParticipant participant;

  const ApiMultisigAuthSession({
    required this.sessionId,
    required this.participantId,
    required this.accessToken,
    required this.refreshToken,
    required this.admissionSecretKey,
    required this.admissionPublicKey,
    required this.deliverySecretKey,
    required this.deliveryPublicKey,
    required this.accessTokenExpiresAt,
    required this.refreshTokenExpiresAt,
    required this.state,
    required this.participant,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      participantId.hashCode ^
      accessToken.hashCode ^
      refreshToken.hashCode ^
      admissionSecretKey.hashCode ^
      admissionPublicKey.hashCode ^
      deliverySecretKey.hashCode ^
      deliveryPublicKey.hashCode ^
      accessTokenExpiresAt.hashCode ^
      refreshTokenExpiresAt.hashCode ^
      state.hashCode ^
      participant.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigAuthSession &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          participantId == other.participantId &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          admissionSecretKey == other.admissionSecretKey &&
          admissionPublicKey == other.admissionPublicKey &&
          deliverySecretKey == other.deliverySecretKey &&
          deliveryPublicKey == other.deliveryPublicKey &&
          accessTokenExpiresAt == other.accessTokenExpiresAt &&
          refreshTokenExpiresAt == other.refreshTokenExpiresAt &&
          state == other.state &&
          participant == other.participant;
}

class ApiMultisigAuthUpdate {
  final String sessionId;
  final String participantId;
  final String accessToken;
  final String refreshToken;
  final String admissionPublicKey;
  final String deliverySecretKey;
  final String deliveryPublicKey;
  final BigInt accessTokenExpiresAt;
  final BigInt refreshTokenExpiresAt;
  final bool resumed;

  const ApiMultisigAuthUpdate({
    required this.sessionId,
    required this.participantId,
    required this.accessToken,
    required this.refreshToken,
    required this.admissionPublicKey,
    required this.deliverySecretKey,
    required this.deliveryPublicKey,
    required this.accessTokenExpiresAt,
    required this.refreshTokenExpiresAt,
    required this.resumed,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      participantId.hashCode ^
      accessToken.hashCode ^
      refreshToken.hashCode ^
      admissionPublicKey.hashCode ^
      deliverySecretKey.hashCode ^
      deliveryPublicKey.hashCode ^
      accessTokenExpiresAt.hashCode ^
      refreshTokenExpiresAt.hashCode ^
      resumed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigAuthUpdate &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          participantId == other.participantId &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          admissionPublicKey == other.admissionPublicKey &&
          deliverySecretKey == other.deliverySecretKey &&
          deliveryPublicKey == other.deliveryPublicKey &&
          accessTokenExpiresAt == other.accessTokenExpiresAt &&
          refreshTokenExpiresAt == other.refreshTokenExpiresAt &&
          resumed == other.resumed;
}

class ApiMultisigBackupArtifact {
  final String artifactJson;
  final String backupHash;
  final String vaultAddress;

  const ApiMultisigBackupArtifact({
    required this.artifactJson,
    required this.backupHash,
    required this.vaultAddress,
  });

  @override
  int get hashCode =>
      artifactJson.hashCode ^ backupHash.hashCode ^ vaultAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigBackupArtifact &&
          runtimeType == other.runtimeType &&
          artifactJson == other.artifactJson &&
          backupHash == other.backupHash &&
          vaultAddress == other.vaultAddress;
}

class ApiMultisigBackupPassword {
  final String displayPassword;
  final String canonicalPassword;
  final String checksum;

  const ApiMultisigBackupPassword({
    required this.displayPassword,
    required this.canonicalPassword,
    required this.checksum,
  });

  @override
  int get hashCode =>
      displayPassword.hashCode ^ canonicalPassword.hashCode ^ checksum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigBackupPassword &&
          runtimeType == other.runtimeType &&
          displayPassword == other.displayPassword &&
          canonicalPassword == other.canonicalPassword &&
          checksum == other.checksum;
}

class ApiMultisigBackupVerification {
  final String backupHash;
  final String vaultAddress;
  final String sessionId;
  final String participantId;
  final int threshold;
  final int participantCount;
  final String rosterHash;
  final String admissionSecretKey;
  final String admissionPublicKey;
  final String deliverySecretKey;
  final String deliveryPublicKey;
  final String keyPackageB64;
  final String groupPublicPackageJson;
  final String groupPublicPackageHash;

  const ApiMultisigBackupVerification({
    required this.backupHash,
    required this.vaultAddress,
    required this.sessionId,
    required this.participantId,
    required this.threshold,
    required this.participantCount,
    required this.rosterHash,
    required this.admissionSecretKey,
    required this.admissionPublicKey,
    required this.deliverySecretKey,
    required this.deliveryPublicKey,
    required this.keyPackageB64,
    required this.groupPublicPackageJson,
    required this.groupPublicPackageHash,
  });

  @override
  int get hashCode =>
      backupHash.hashCode ^
      vaultAddress.hashCode ^
      sessionId.hashCode ^
      participantId.hashCode ^
      threshold.hashCode ^
      participantCount.hashCode ^
      rosterHash.hashCode ^
      admissionSecretKey.hashCode ^
      admissionPublicKey.hashCode ^
      deliverySecretKey.hashCode ^
      deliveryPublicKey.hashCode ^
      keyPackageB64.hashCode ^
      groupPublicPackageJson.hashCode ^
      groupPublicPackageHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigBackupVerification &&
          runtimeType == other.runtimeType &&
          backupHash == other.backupHash &&
          vaultAddress == other.vaultAddress &&
          sessionId == other.sessionId &&
          participantId == other.participantId &&
          threshold == other.threshold &&
          participantCount == other.participantCount &&
          rosterHash == other.rosterHash &&
          admissionSecretKey == other.admissionSecretKey &&
          admissionPublicKey == other.admissionPublicKey &&
          deliverySecretKey == other.deliverySecretKey &&
          deliveryPublicKey == other.deliveryPublicKey &&
          keyPackageB64 == other.keyPackageB64 &&
          groupPublicPackageJson == other.groupPublicPackageJson &&
          groupPublicPackageHash == other.groupPublicPackageHash;
}

class ApiMultisigCreateAdvance {
  final ApiMultisigSession session;
  final String localStateJson;
  final String phase;
  final String detail;
  final List<String> waitingForParticipantIds;
  final int round1Count;
  final int round2Count;
  final bool dkgCompleteSubmitted;
  final String? keyPackageB64;
  final String? groupPublicPackageJson;
  final String? groupPublicPackageHash;

  const ApiMultisigCreateAdvance({
    required this.session,
    required this.localStateJson,
    required this.phase,
    required this.detail,
    required this.waitingForParticipantIds,
    required this.round1Count,
    required this.round2Count,
    required this.dkgCompleteSubmitted,
    this.keyPackageB64,
    this.groupPublicPackageJson,
    this.groupPublicPackageHash,
  });

  @override
  int get hashCode =>
      session.hashCode ^
      localStateJson.hashCode ^
      phase.hashCode ^
      detail.hashCode ^
      waitingForParticipantIds.hashCode ^
      round1Count.hashCode ^
      round2Count.hashCode ^
      dkgCompleteSubmitted.hashCode ^
      keyPackageB64.hashCode ^
      groupPublicPackageJson.hashCode ^
      groupPublicPackageHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigCreateAdvance &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          localStateJson == other.localStateJson &&
          phase == other.phase &&
          detail == other.detail &&
          waitingForParticipantIds == other.waitingForParticipantIds &&
          round1Count == other.round1Count &&
          round2Count == other.round2Count &&
          dkgCompleteSubmitted == other.dkgCompleteSubmitted &&
          keyPackageB64 == other.keyPackageB64 &&
          groupPublicPackageJson == other.groupPublicPackageJson &&
          groupPublicPackageHash == other.groupPublicPackageHash;
}

class ApiMultisigParticipant {
  final String participantId;
  final String? label;
  final String admissionPublicKey;
  final String deliveryPublicKey;
  final BigInt joinedAt;
  final bool dkgCompleted;

  const ApiMultisigParticipant({
    required this.participantId,
    this.label,
    required this.admissionPublicKey,
    required this.deliveryPublicKey,
    required this.joinedAt,
    required this.dkgCompleted,
  });

  @override
  int get hashCode =>
      participantId.hashCode ^
      label.hashCode ^
      admissionPublicKey.hashCode ^
      deliveryPublicKey.hashCode ^
      joinedAt.hashCode ^
      dkgCompleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigParticipant &&
          runtimeType == other.runtimeType &&
          participantId == other.participantId &&
          label == other.label &&
          admissionPublicKey == other.admissionPublicKey &&
          deliveryPublicKey == other.deliveryPublicKey &&
          joinedAt == other.joinedAt &&
          dkgCompleted == other.dkgCompleted;
}

class ApiMultisigParticipantIdentity {
  final String admissionSecretKey;
  final String admissionPublicKey;
  final String deliverySecretKey;
  final String deliveryPublicKey;

  const ApiMultisigParticipantIdentity({
    required this.admissionSecretKey,
    required this.admissionPublicKey,
    required this.deliverySecretKey,
    required this.deliveryPublicKey,
  });

  @override
  int get hashCode =>
      admissionSecretKey.hashCode ^
      admissionPublicKey.hashCode ^
      deliverySecretKey.hashCode ^
      deliveryPublicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigParticipantIdentity &&
          runtimeType == other.runtimeType &&
          admissionSecretKey == other.admissionSecretKey &&
          admissionPublicKey == other.admissionPublicKey &&
          deliverySecretKey == other.deliverySecretKey &&
          deliveryPublicKey == other.deliveryPublicKey;
}

class ApiMultisigSession {
  final String sessionId;
  final String state;
  final String creatorParticipantId;
  final int? threshold;
  final String? rosterHash;
  final String? groupPublicPackageHash;
  final List<ApiMultisigParticipant> participants;
  final BigInt createdAt;
  final BigInt updatedAt;

  const ApiMultisigSession({
    required this.sessionId,
    required this.state,
    required this.creatorParticipantId,
    this.threshold,
    this.rosterHash,
    this.groupPublicPackageHash,
    required this.participants,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      state.hashCode ^
      creatorParticipantId.hashCode ^
      threshold.hashCode ^
      rosterHash.hashCode ^
      groupPublicPackageHash.hashCode ^
      participants.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigSession &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          state == other.state &&
          creatorParticipantId == other.creatorParticipantId &&
          threshold == other.threshold &&
          rosterHash == other.rosterHash &&
          groupPublicPackageHash == other.groupPublicPackageHash &&
          participants == other.participants &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class ApiMultisigSessionEvent {
  final PlatformInt64 cursor;
  final String sessionId;
  final String kind;
  final String? actorParticipantId;
  final String payloadJson;
  final BigInt createdAt;

  const ApiMultisigSessionEvent({
    required this.cursor,
    required this.sessionId,
    required this.kind,
    this.actorParticipantId,
    required this.payloadJson,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      cursor.hashCode ^
      sessionId.hashCode ^
      kind.hashCode ^
      actorParticipantId.hashCode ^
      payloadJson.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigSessionEvent &&
          runtimeType == other.runtimeType &&
          cursor == other.cursor &&
          sessionId == other.sessionId &&
          kind == other.kind &&
          actorParticipantId == other.actorParticipantId &&
          payloadJson == other.payloadJson &&
          createdAt == other.createdAt;
}

class ApiMultisigSessionEvents {
  final PlatformInt64 cursor;
  final List<ApiMultisigSessionEvent> events;

  const ApiMultisigSessionEvents({required this.cursor, required this.events});

  @override
  int get hashCode => cursor.hashCode ^ events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigSessionEvents &&
          runtimeType == other.runtimeType &&
          cursor == other.cursor &&
          events == other.events;
}

class ApiMultisigSignedPczt {
  final String localStateJson;
  final Uint8List signedPcztBytes;

  const ApiMultisigSignedPczt({
    required this.localStateJson,
    required this.signedPcztBytes,
  });

  @override
  int get hashCode => localStateJson.hashCode ^ signedPcztBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigSignedPczt &&
          runtimeType == other.runtimeType &&
          localStateJson == other.localStateJson &&
          signedPcztBytes == other.signedPcztBytes;
}

class ApiMultisigSigningAdvance {
  final String localStateJson;
  final String detail;
  final bool submitted;

  const ApiMultisigSigningAdvance({
    required this.localStateJson,
    required this.detail,
    required this.submitted,
  });

  @override
  int get hashCode =>
      localStateJson.hashCode ^ detail.hashCode ^ submitted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigSigningAdvance &&
          runtimeType == other.runtimeType &&
          localStateJson == other.localStateJson &&
          detail == other.detail &&
          submitted == other.submitted;
}

class ApiMultisigSigningInbox {
  final PlatformInt64 cursor;
  final List<ApiMultisigSigningMessage> messages;

  const ApiMultisigSigningInbox({required this.cursor, required this.messages});

  @override
  int get hashCode => cursor.hashCode ^ messages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigSigningInbox &&
          runtimeType == other.runtimeType &&
          cursor == other.cursor &&
          messages == other.messages;
}

class ApiMultisigSigningMessage {
  final PlatformInt64 cursor;
  final String messageId;
  final String sessionId;
  final String kind;
  final String fromParticipantId;
  final String? toParticipantId;
  final String? relatedId;
  final String? plaintextJson;
  final String? decryptError;
  final BigInt createdAt;

  const ApiMultisigSigningMessage({
    required this.cursor,
    required this.messageId,
    required this.sessionId,
    required this.kind,
    required this.fromParticipantId,
    this.toParticipantId,
    this.relatedId,
    this.plaintextJson,
    this.decryptError,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      cursor.hashCode ^
      messageId.hashCode ^
      sessionId.hashCode ^
      kind.hashCode ^
      fromParticipantId.hashCode ^
      toParticipantId.hashCode ^
      relatedId.hashCode ^
      plaintextJson.hashCode ^
      decryptError.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigSigningMessage &&
          runtimeType == other.runtimeType &&
          cursor == other.cursor &&
          messageId == other.messageId &&
          sessionId == other.sessionId &&
          kind == other.kind &&
          fromParticipantId == other.fromParticipantId &&
          toParticipantId == other.toParticipantId &&
          relatedId == other.relatedId &&
          plaintextJson == other.plaintextJson &&
          decryptError == other.decryptError &&
          createdAt == other.createdAt;
}

class ApiMultisigSigningRequest {
  final String signingRequestId;
  final String sessionId;
  final String requesterParticipantId;
  final List<String> selectedParticipantIds;

  /// Coordinator-derived progress: selected signers whose Round 1 / Round 2
  /// envelopes were relayed, and participants that posted a broadcast
  /// result. Derived from message metadata server-side.
  final List<String> round1ParticipantIds;
  final List<String> round2ParticipantIds;
  final List<String> broadcastParticipantIds;
  final String state;
  final BigInt createdAt;
  final BigInt updatedAt;
  final String pcztHash;

  const ApiMultisigSigningRequest({
    required this.signingRequestId,
    required this.sessionId,
    required this.requesterParticipantId,
    required this.selectedParticipantIds,
    required this.round1ParticipantIds,
    required this.round2ParticipantIds,
    required this.broadcastParticipantIds,
    required this.state,
    required this.createdAt,
    required this.updatedAt,
    required this.pcztHash,
  });

  @override
  int get hashCode =>
      signingRequestId.hashCode ^
      sessionId.hashCode ^
      requesterParticipantId.hashCode ^
      selectedParticipantIds.hashCode ^
      round1ParticipantIds.hashCode ^
      round2ParticipantIds.hashCode ^
      broadcastParticipantIds.hashCode ^
      state.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      pcztHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigSigningRequest &&
          runtimeType == other.runtimeType &&
          signingRequestId == other.signingRequestId &&
          sessionId == other.sessionId &&
          requesterParticipantId == other.requesterParticipantId &&
          selectedParticipantIds == other.selectedParticipantIds &&
          round1ParticipantIds == other.round1ParticipantIds &&
          round2ParticipantIds == other.round2ParticipantIds &&
          broadcastParticipantIds == other.broadcastParticipantIds &&
          state == other.state &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          pcztHash == other.pcztHash;
}

class ApiMultisigThresholdParams {
  final int threshold;
  final int participantCount;

  const ApiMultisigThresholdParams({
    required this.threshold,
    required this.participantCount,
  });

  @override
  int get hashCode => threshold.hashCode ^ participantCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigThresholdParams &&
          runtimeType == other.runtimeType &&
          threshold == other.threshold &&
          participantCount == other.participantCount;
}

class ApiMultisigTokens {
  final String sessionId;
  final String participantId;
  final String accessToken;
  final String refreshToken;
  final BigInt accessTokenExpiresAt;
  final BigInt refreshTokenExpiresAt;

  const ApiMultisigTokens({
    required this.sessionId,
    required this.participantId,
    required this.accessToken,
    required this.refreshToken,
    required this.accessTokenExpiresAt,
    required this.refreshTokenExpiresAt,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      participantId.hashCode ^
      accessToken.hashCode ^
      refreshToken.hashCode ^
      accessTokenExpiresAt.hashCode ^
      refreshTokenExpiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMultisigTokens &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          participantId == other.participantId &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          accessTokenExpiresAt == other.accessTokenExpiresAt &&
          refreshTokenExpiresAt == other.refreshTokenExpiresAt;
}

class ApiPreparedMultisigSigningRequest {
  final String signingRequestId;
  final String sessionId;
  final String requesterParticipantId;
  final List<String> selectedParticipantIds;
  final String requestJson;
  final String idempotencyKey;
  final String pcztHash;
  final BigInt createdAt;

  const ApiPreparedMultisigSigningRequest({
    required this.signingRequestId,
    required this.sessionId,
    required this.requesterParticipantId,
    required this.selectedParticipantIds,
    required this.requestJson,
    required this.idempotencyKey,
    required this.pcztHash,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      signingRequestId.hashCode ^
      sessionId.hashCode ^
      requesterParticipantId.hashCode ^
      selectedParticipantIds.hashCode ^
      requestJson.hashCode ^
      idempotencyKey.hashCode ^
      pcztHash.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPreparedMultisigSigningRequest &&
          runtimeType == other.runtimeType &&
          signingRequestId == other.signingRequestId &&
          sessionId == other.sessionId &&
          requesterParticipantId == other.requesterParticipantId &&
          selectedParticipantIds == other.selectedParticipantIds &&
          requestJson == other.requestJson &&
          idempotencyKey == other.idempotencyKey &&
          pcztHash == other.pcztHash &&
          createdAt == other.createdAt;
}
