// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `sanitized_payment_uri_error`

/// Parses a cross-chain payment URI into the parser's versioned JSON contract.
///
/// This only validates protocol syntax. The caller must resolve supported
/// networks and assets, preserve required payment conditions, and obtain user
/// approval before creating a payment. No endpoint in the request is fetched.
Future<String> parseCrossChainPaymentUri({required String uri}) =>
    RustLib.instance.api.crateApiPaymentUriParseCrossChainPaymentUri(uri: uri);
