// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `catch`, `phase_name`

Stream<ApiPirProgressEvent> runStartupPir({
  required String dbPath,
  required String network,
  String? spendServerUrlOverride,
  String? witnessServerUrlOverride,
}) => RustLib.instance.api.crateApiPirRunStartupPir(
  dbPath: dbPath,
  network: network,
  spendServerUrlOverride: spendServerUrlOverride,
  witnessServerUrlOverride: witnessServerUrlOverride,
);

void cancelStartupPir() => RustLib.instance.api.crateApiPirCancelStartupPir();

bool isStartupPirRunning() =>
    RustLib.instance.api.crateApiPirIsStartupPirRunning();

class ApiPirProgressEvent {
  final String phase;
  final int completed;
  final int total;
  final int witnessesInserted;
  final String? skippedReason;

  const ApiPirProgressEvent({
    required this.phase,
    required this.completed,
    required this.total,
    required this.witnessesInserted,
    this.skippedReason,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      completed.hashCode ^
      total.hashCode ^
      witnessesInserted.hashCode ^
      skippedReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPirProgressEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          completed == other.completed &&
          total == other.total &&
          witnessesInserted == other.witnessesInserted &&
          skippedReason == other.skippedReason;
}
