// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `account_ufvk`, `catch`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`

Future<ApiPrivateStateObjectReference> derivePrivateStateObjectReference({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String namespace,
  required String itemKey,
}) => RustLib.instance.api
    .crateApiPrivateStateSyncDerivePrivateStateObjectReference(
      dbPath: dbPath,
      network: network,
      accountUuid: accountUuid,
      namespace: namespace,
      itemKey: itemKey,
    );

Future<ApiPrivateStateEnvelope> sealPrivateStateObject({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String namespace,
  required String itemKey,
  required List<int> plaintext,
}) => RustLib.instance.api.crateApiPrivateStateSyncSealPrivateStateObject(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  namespace: namespace,
  itemKey: itemKey,
  plaintext: plaintext,
);

Future<Uint8List> openPrivateStateObject({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String namespace,
  required String itemKey,
  required ApiPrivateStateEnvelope envelope,
}) => RustLib.instance.api.crateApiPrivateStateSyncOpenPrivateStateObject(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  namespace: namespace,
  itemKey: itemKey,
  envelope: envelope,
);

Future<ApiPrivateStateRequestAuthorization> authorizePrivateStateRequest({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String namespace,
  required String itemKey,
  required String method,
  required String challengeBase64,
  required String audience,
  required BigInt expiresAtSeconds,
  ApiPrivateStateEnvelope? envelope,
}) => RustLib.instance.api.crateApiPrivateStateSyncAuthorizePrivateStateRequest(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  namespace: namespace,
  itemKey: itemKey,
  method: method,
  challengeBase64: challengeBase64,
  audience: audience,
  expiresAtSeconds: expiresAtSeconds,
  envelope: envelope,
);

/// Verifies an opaque request authorization without access to a wallet UFVK.
///
/// Deployments must additionally check the challenge's server-side lifetime,
/// single-use state, and expected audience before accepting the request.
Future<void> verifyPrivateStateRequestAuthorization({
  required ApiPrivateStateRequestAuthorization authorization,
}) => RustLib.instance.api
    .crateApiPrivateStateSyncVerifyPrivateStateRequestAuthorization(
      authorization: authorization,
    );

/// Verifies that an opaque object reference is self-certifying before a
/// server allocates challenge state for it.
Future<void> verifyPrivateStateObjectReference({
  required ApiPrivateStateObjectReference reference,
}) => RustLib.instance.api
    .crateApiPrivateStateSyncVerifyPrivateStateObjectReference(
      reference: reference,
    );

/// Verifies that a PUT authorization is bound to the supplied opaque envelope.
Future<void> verifyPrivateStatePutAuthorizationContent({
  required ApiPrivateStateEnvelope envelope,
  required ApiPrivateStateRequestAuthorization authorization,
}) => RustLib.instance.api
    .crateApiPrivateStateSyncVerifyPrivateStatePutAuthorizationContent(
      envelope: envelope,
      authorization: authorization,
    );

class ApiPrivateStateEnvelope {
  final int protocolVersion;
  final String objectId;
  final String authPublicKeyBase64;
  final String nonceBase64;
  final String ciphertextBase64;
  final String signatureBase64;

  const ApiPrivateStateEnvelope({
    required this.protocolVersion,
    required this.objectId,
    required this.authPublicKeyBase64,
    required this.nonceBase64,
    required this.ciphertextBase64,
    required this.signatureBase64,
  });

  @override
  int get hashCode =>
      protocolVersion.hashCode ^
      objectId.hashCode ^
      authPublicKeyBase64.hashCode ^
      nonceBase64.hashCode ^
      ciphertextBase64.hashCode ^
      signatureBase64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPrivateStateEnvelope &&
          runtimeType == other.runtimeType &&
          protocolVersion == other.protocolVersion &&
          objectId == other.objectId &&
          authPublicKeyBase64 == other.authPublicKeyBase64 &&
          nonceBase64 == other.nonceBase64 &&
          ciphertextBase64 == other.ciphertextBase64 &&
          signatureBase64 == other.signatureBase64;
}

class ApiPrivateStateObjectReference {
  final int protocolVersion;
  final String objectId;
  final String authPublicKeyBase64;

  const ApiPrivateStateObjectReference({
    required this.protocolVersion,
    required this.objectId,
    required this.authPublicKeyBase64,
  });

  @override
  int get hashCode =>
      protocolVersion.hashCode ^
      objectId.hashCode ^
      authPublicKeyBase64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPrivateStateObjectReference &&
          runtimeType == other.runtimeType &&
          protocolVersion == other.protocolVersion &&
          objectId == other.objectId &&
          authPublicKeyBase64 == other.authPublicKeyBase64;
}

class ApiPrivateStateRequestAuthorization {
  final int protocolVersion;
  final String objectId;
  final String authPublicKeyBase64;
  final String method;
  final String challengeBase64;
  final String audience;
  final BigInt expiresAtSeconds;
  final String contentHashBase64;
  final String signatureBase64;

  const ApiPrivateStateRequestAuthorization({
    required this.protocolVersion,
    required this.objectId,
    required this.authPublicKeyBase64,
    required this.method,
    required this.challengeBase64,
    required this.audience,
    required this.expiresAtSeconds,
    required this.contentHashBase64,
    required this.signatureBase64,
  });

  @override
  int get hashCode =>
      protocolVersion.hashCode ^
      objectId.hashCode ^
      authPublicKeyBase64.hashCode ^
      method.hashCode ^
      challengeBase64.hashCode ^
      audience.hashCode ^
      expiresAtSeconds.hashCode ^
      contentHashBase64.hashCode ^
      signatureBase64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPrivateStateRequestAuthorization &&
          runtimeType == other.runtimeType &&
          protocolVersion == other.protocolVersion &&
          objectId == other.objectId &&
          authPublicKeyBase64 == other.authPublicKeyBase64 &&
          method == other.method &&
          challengeBase64 == other.challengeBase64 &&
          audience == other.audience &&
          expiresAtSeconds == other.expiresAtSeconds &&
          contentHashBase64 == other.contentHashBase64 &&
          signatureBase64 == other.signatureBase64;
}
