// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Keep wallet consensus parameters aligned with the local Ironwood regtest
/// node. Production builds leave the default activation-at-height-1 behavior.
Future<void> configureRegtestIronwoodActivationHeight({required int height}) =>
    RustLib.instance.api.crateApiSimpleConfigureRegtestIronwoodActivationHeight(
      height: height,
    );

/// Enables Regtest-speed migration timing on Testnet only. Mainnet and
/// Regtest consensus behavior are unaffected.
Future<void> configureFastTestnetMigration({required bool enabled}) => RustLib
    .instance
    .api
    .crateApiSimpleConfigureFastTestnetMigration(enabled: enabled);

/// Records the `ZCASH_PRIVATE_TRANSPARENT_RECOVERY` development flag. Without
/// it, private queries never select private transparent recovery and no
/// transparent policy is raised; an explicit toggle-off still lowers one.
Future<void> configurePrivateTransparentRecovery({required bool enabled}) =>
    RustLib.instance.api.crateApiSimpleConfigurePrivateTransparentRecovery(
      enabled: enabled,
    );
