// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../wallet/swap_receiving/receive.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Resumes the account's draft or reserves the lowest eligible index. Its key is
/// scanned from the next unscanned block until it closes, and quoting later
/// requires that scanning to reach the tip without finding a payment. Does not
/// start or restart ordinary wallet sync.
Future<ReceiveReservation> prepareReceiveReservation({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required BigInt liveTip,
}) => RustLib.instance.api.crateApiSwapReceivePrepareReceiveReservation(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  liveTip: liveTip,
);

/// Persists an unknown outcome and scan watch just before a provider quote request
/// leaves the device, and returns the request's identity. `deadline_seconds` is the
/// deposit deadline the request sends.
Future<String> beginReceiveQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required PlatformInt64 reservationId,
  required PlatformInt64 deadlineSeconds,
}) => RustLib.instance.api.crateApiSwapReceiveBeginReceiveQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  reservationId: reservationId,
  deadlineSeconds: deadlineSeconds,
);

/// Saves accepted payment instructions even if the requesting UI has changed.
Future<void> recordReceiveQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required String requestId,
  required String operationId,
  String? depositMemo,
  required PlatformInt64 deadlineSeconds,
}) => RustLib.instance.api.crateApiSwapReceiveRecordReceiveQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  requestId: requestId,
  operationId: operationId,
  depositMemo: depositMemo,
  deadlineSeconds: deadlineSeconds,
);

/// Removes only a definitively rejected request watch; never call for a timeout.
Future<void> rejectReceiveQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required String requestId,
}) => RustLib.instance.api.crateApiSwapReceiveRejectReceiveQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  requestId: requestId,
);

/// Locks the accepted draft before exposing provider funding instructions, and
/// returns the instructions to show.
Future<ReceiveDepositInstruction> startReceiveQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required String requestId,
}) => RustLib.instance.api.crateApiSwapReceiveStartReceiveQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  requestId: requestId,
);

/// Returns operations whose provider status needs refreshing.
Future<List<ReceiveQuoteStatusRequest>> receiveQuotesDue({
  required String dbPath,
  required String networkName,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSwapReceiveReceiveQuotesDue(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
);

/// Saves a successful status response using the request start time to reject stale observations.
Future<void> observeReceiveQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required String requestId,
  required SwapProviderStatus status,
  required bool funded,
  required PlatformInt64 checkedAtSeconds,
}) => RustLib.instance.api.crateApiSwapReceiveObserveReceiveQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  requestId: requestId,
  status: status,
  funded: funded,
  checkedAtSeconds: checkedAtSeconds,
);

/// Closes settled paid reservations and releases abandoned unpaid ones whose
/// addresses local scanning shows are still empty.
Future<void> reapReceiveReservations({
  required String dbPath,
  required String networkName,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSwapReceiveReapReceiveReservations(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
);

/// The deposit instructions of a started incoming quote: the only ones to show.
class ReceiveDepositInstruction {
  final String address;
  final String? memo;

  const ReceiveDepositInstruction({required this.address, this.memo});

  @override
  int get hashCode => address.hashCode ^ memo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiveDepositInstruction &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          memo == other.memo;
}

/// Provider lookup for a persisted quote, including quotes never started in the UI.
class ReceiveQuoteStatusRequest {
  final String requestId;
  final String operationId;
  final String? depositMemo;

  const ReceiveQuoteStatusRequest({
    required this.requestId,
    required this.operationId,
    this.depositMemo,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^ operationId.hashCode ^ depositMemo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiveQuoteStatusRequest &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          operationId == other.operationId &&
          depositMemo == other.depositMemo;
}

/// An account-scoped durable receive draft, whose key is scanned from issuance.
class ReceiveReservation {
  final PlatformInt64 id;
  final String address;

  const ReceiveReservation({required this.id, required this.address});

  @override
  int get hashCode => id.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiveReservation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          address == other.address;
}

/// The NEAR 1Click status fields that decide when a swap key stops scanning.
/// Amounts are base-unit decimal strings, as the provider reports them.
class SwapProviderStatus {
  final String status;
  final String? swapType;
  final String? refundedAmount;
  final String? amountOut;
  final PlatformInt64? deadlineSeconds;

  const SwapProviderStatus({
    required this.status,
    this.swapType,
    this.refundedAmount,
    this.amountOut,
    this.deadlineSeconds,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      swapType.hashCode ^
      refundedAmount.hashCode ^
      amountOut.hashCode ^
      deadlineSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapProviderStatus &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          swapType == other.swapType &&
          refundedAmount == other.refundedAmount &&
          amountOut == other.amountOut &&
          deadlineSeconds == other.deadlineSeconds;
}
