// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `network`

/// Resumes a draft or reserves the lowest eligible index and verifies it through PIR.
/// Does not start or restart ordinary wallet sync.
Future<ReceiveReservation> prepareReceiveReservation({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required BigInt liveTip,
}) => RustLib.instance.api.crateApiSwapReceivePrepareReceiveReservation(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  liveTip: liveTip,
);

/// Persists an unknown outcome and scan watch before sending a provider quote request.
Future<void> beginReceiveQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required PlatformInt64 reservationId,
  required String requestId,
}) => RustLib.instance.api.crateApiSwapReceiveBeginReceiveQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  reservationId: reservationId,
  requestId: requestId,
);

/// Saves accepted payment instructions even if the requesting UI has changed.
Future<void> recordReceiveQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required String requestId,
  required String operationId,
  String? depositMemo,
  required PlatformInt64 deadlineSeconds,
}) => RustLib.instance.api.crateApiSwapReceiveRecordReceiveQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  requestId: requestId,
  operationId: operationId,
  depositMemo: depositMemo,
  deadlineSeconds: deadlineSeconds,
);

/// Removes only a definitively rejected request watch; never call for a timeout.
Future<void> rejectReceiveQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required String requestId,
}) => RustLib.instance.api.crateApiSwapReceiveRejectReceiveQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  requestId: requestId,
);

/// Locks the accepted draft before exposing provider funding instructions.
Future<void> startReceiveQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required String operationId,
}) => RustLib.instance.api.crateApiSwapReceiveStartReceiveQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  operationId: operationId,
);

/// Returns operations whose provider status needs refreshing.
Future<List<ReceiveQuoteStatusRequest>> receiveQuotesDue({
  required String dbPath,
  required String networkName,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSwapReceiveReceiveQuotesDue(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
);

/// Saves a successful status response using the request start time to reject stale observations.
Future<void> observeReceiveQuote({
  required String dbPath,
  required String networkName,
  required String accountUuid,
  required String requestId,
  required String status,
  required bool funded,
  required PlatformInt64 checkedAtSeconds,
}) => RustLib.instance.api.crateApiSwapReceiveObserveReceiveQuote(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
  requestId: requestId,
  status: status,
  funded: funded,
  checkedAtSeconds: checkedAtSeconds,
);

/// Rechecks eligible abandoned addresses against PIR and releases only verified empty ones.
Future<int> reapReceiveReservations({
  required String dbPath,
  required String networkName,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSwapReceiveReapReceiveReservations(
  dbPath: dbPath,
  networkName: networkName,
  accountUuid: accountUuid,
);

/// Provider lookup for a persisted quote, including quotes never started in the UI.
class ReceiveQuoteStatusRequest {
  final String requestId;
  final String operationId;
  final String? depositMemo;

  const ReceiveQuoteStatusRequest({
    required this.requestId,
    required this.operationId,
    this.depositMemo,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^ operationId.hashCode ^ depositMemo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiveQuoteStatusRequest &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          operationId == other.operationId &&
          depositMemo == other.depositMemo;
}

/// An account-scoped durable receive draft; its address has passed current PIR verification.
class ReceiveReservation {
  final PlatformInt64 id;
  final BigInt index;
  final String address;

  const ReceiveReservation({
    required this.id,
    required this.index,
    required this.address,
  });

  @override
  int get hashCode => id.hashCode ^ index.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiveReservation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          index == other.index &&
          address == other.address;
}
