// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ed25519_signing_key`, `hex20`, `hex32`, `hex33`

/// Derive the displayable b2z (BTC→ZEC) material for `swap_id` from the wallet
/// `seed` (hex) and the solver's verified public Phase0 half.
///
/// `solver_ak_sec1` (66 hex chars / 33 bytes), `solver_nsk_le` (64/32),
/// `solver_b_b` (66/33), `solver_h_b` (64/32) come from a poold entry the
/// caller has already re-verified. `network` is `mainnet` | `testnet` |
/// `regtest`. Pure and offline; no chain or network I/O.
Future<ZwapB2zMaterial> zwapDeriveB2ZMaterial({
  required String seedHex,
  required String swapId,
  required String solverAkSec1,
  required String solverNskLe,
  required String solverBB,
  required String solverHB,
  required int t1,
  required int t2,
  required String network,
}) => RustLib.instance.api.crateApiSwapZwapZwapDeriveB2ZMaterial(
  seedHex: seedHex,
  swapId: swapId,
  solverAkSec1: solverAkSec1,
  solverNskLe: solverNskLe,
  solverBB: solverBB,
  solverHB: solverHB,
  t1: t1,
  t2: t2,
  network: network,
);

/// Derive the wallet's public Phase0 contribution for `swap_id`. The private
/// scalar `k_a` and `secret` are NOT returned — only their commitments and the
/// public Orchard half.
Future<ZwapInitiatorHalf> zwapDeriveInitiatorHalf({
  required String seedHex,
  required String swapId,
}) => RustLib.instance.api.crateApiSwapZwapZwapDeriveInitiatorHalf(
  seedHex: seedHex,
  swapId: swapId,
);

/// Reveal the wallet's per-swap swap secret for `swap_id` (the `SecretReveal`
/// step). Only call when the orderbook FSM says the wallet owns the reveal.
Future<String> zwapRevealSecretHex({
  required String seedHex,
  required String swapId,
}) => RustLib.instance.api.crateApiSwapZwapZwapRevealSecretHex(
  seedHex: seedHex,
  swapId: swapId,
);

/// The wallet's own spend-auth scalar `k_a` (BE hex) for `swap_id` — needed to
/// reconstruct the joint `ask` once the counterparty reveals `k_b` on-chain.
Future<String> zwapKUserBeHex({
  required String seedHex,
  required String swapId,
}) => RustLib.instance.api.crateApiSwapZwapZwapKUserBeHex(
  seedHex: seedHex,
  swapId: swapId,
);

/// Reconstruct the joint Orchard spend-auth scalar `ask = (k_a + k_b) mod q`
/// (LE hex, the form `orchard_spend` consumes) from the two BE scalars. `k_a`
/// is the wallet's own; `k_b` is the solver's, revealed in its on-chain claim.
Future<String> zwapJointAskLeHex({
  required String kABeHex,
  required String kBBeHex,
}) => RustLib.instance.api.crateApiSwapZwapZwapJointAskLeHex(
  kABeHex: kABeHex,
  kBBeHex: kBBeHex,
);

/// Trial-decrypt the joint note from compact blocks. `request_json` is the
/// `orchard-wasm` DecryptRequest (ivk, diversifier, blocks, frontier_hex, …);
/// returns the DecryptResponse JSON (found notes + tree_size).
Future<String> zwapOrchardTrialDecrypt({required String requestJson}) => RustLib
    .instance
    .api
    .crateApiSwapZwapZwapOrchardTrialDecrypt(requestJson: requestJson);

/// Build + prove + sign + serialize the joint-note sweep. `request_json` is the
/// `orchard-wasm` SpendRequest (ask, nk, rivk, note, merkle_path, dest, …);
/// returns the SpendResponse JSON (raw_tx_hex + txid) ready to broadcast.
Future<String> zwapOrchardSpend({required String requestJson}) => RustLib
    .instance
    .api
    .crateApiSwapZwapZwapOrchardSpend(requestJson: requestJson);

/// Derive the joint Orchard unified address + ivk/diversifier from the combined
/// `ak`/`nk`/`rivk` (hex). `request_json` is the `orchard-wasm` DeriveRequest.
Future<String> zwapOrchardDerive({required String requestJson}) => RustLib
    .instance
    .api
    .crateApiSwapZwapZwapOrchardDerive(requestJson: requestJson);

/// Derive the displayable e2z proxy material for `swap_id` from the wallet
/// `seed` (hex), the solver's verified relayed half, and the proxy escrow terms.
/// `initiator_evm_addr` is the user's own ETH wallet (the refund destination).
/// `token_addr` is the zero address for native ETH. Pure/offline.
Future<ZwapE2zMaterial> zwapDeriveE2ZProxyMaterial({
  required String seedHex,
  required String swapId,
  required String solverAkSec1,
  required String solverNskLe,
  required String solverLockPubkey,
  required String solverRefundPubkey,
  required String solverHB,
  required String solverEvmAddr,
  required String amountWei,
  required String tokenAddr,
  required String t0Abs,
  required String t1Abs,
  required BigInt chainId,
  required String factoryAddr,
  required String implementationAddr,
  required String initiatorEvmAddr,
  required String network,
}) => RustLib.instance.api.crateApiSwapZwapZwapDeriveE2ZProxyMaterial(
  seedHex: seedHex,
  swapId: swapId,
  solverAkSec1: solverAkSec1,
  solverNskLe: solverNskLe,
  solverLockPubkey: solverLockPubkey,
  solverRefundPubkey: solverRefundPubkey,
  solverHB: solverHB,
  solverEvmAddr: solverEvmAddr,
  amountWei: amountWei,
  tokenAddr: tokenAddr,
  t0Abs: t0Abs,
  t1Abs: t1Abs,
  chainId: chainId,
  factoryAddr: factoryAddr,
  implementationAddr: implementationAddr,
  initiatorEvmAddr: initiatorEvmAddr,
  network: network,
);

/// The ed25519 public key (hex) for the wallet seed — the orderbook identity.
Future<String> zwapObIdentityPubkeyHex({required String seedHex}) => RustLib
    .instance
    .api
    .crateApiSwapZwapZwapObIdentityPubkeyHex(seedHex: seedHex);

/// Sign an orderbook auth `challenge` (UTF-8 bytes) with the seed's ed25519 key.
/// Returns the 64-byte signature as hex.
Future<String> zwapObSignChallengeHex({
  required String seedHex,
  required String challenge,
}) => RustLib.instance.api.crateApiSwapZwapZwapObSignChallengeHex(
  seedHex: seedHex,
  challenge: challenge,
);

/// Find a "safe" derive-id for `(seed, base_id)` whose derived spend-auth
/// scalar `k_a < 2^251` — the bound the DLEq/hashbind circuits prove over
/// (matches the SDK `findDleqSafeDeriveId`). Returns `base_id`, else
/// `base_id~1`, `base_id~2`, … (up to 256 tries). A raw `k_a` reduced mod the
/// ~254-bit Pallas order exceeds 2^251 often enough that order creation MUST
/// use a safe id or the prover/matcher rejects it.
Future<String> zwapFindSafeSwapId({
  required String seedHex,
  required String baseId,
}) => RustLib.instance.api.crateApiSwapZwapZwapFindSafeSwapId(
  seedHex: seedHex,
  baseId: baseId,
);

/// Assemble the b2z `feMaterial` inputs for `swap_id` (all hex). The returned
/// fields go verbatim into the order's `feMaterial` (plus `proofKind:"hashbind"`
/// and the `hashbindProof` the caller computes from `k_be_hex`).
Future<ZwapB2zOrderInputs> zwapB2ZOrderInputs({
  required String seedHex,
  required String swapId,
}) => RustLib.instance.api.crateApiSwapZwapZwapB2ZOrderInputs(
  seedHex: seedHex,
  swapId: swapId,
);

/// Assemble the z2b `feMaterial` inputs for `swap_id` (all hex). The returned
/// fields go into the order's `feMaterial` (`refundPubkey`=`claim_pubkey`, no
/// `swapHash`, plus `proofKind:"hashbind"` and the `hashbindProof` the caller
/// computes from `k_be_hex`).
Future<ZwapZ2bOrderInputs> zwapZ2BOrderInputs({
  required String seedHex,
  required String swapId,
}) => RustLib.instance.api.crateApiSwapZwapZwapZ2BOrderInputs(
  seedHex: seedHex,
  swapId: swapId,
);

/// Derive the z2b material for `swap_id` from the wallet `seed` (hex) and the
/// solver's verified public Phase0 half. `solver_ak_sec1` (66 hex/33B),
/// `solver_nsk_le` (64/32), `solver_h_b` (64/32), `solver_refund_pubkey`
/// (66/33), and `solver_swap_hash` (64/32) come from the recover snapshot /
/// re-verified poold entry. Pure and offline.
Future<ZwapZ2bMaterial> zwapDeriveZ2BMaterial({
  required String seedHex,
  required String swapId,
  required String solverAkSec1,
  required String solverNskLe,
  required String solverHB,
  required String solverRefundPubkey,
  required String solverSwapHash,
  required int t1,
  required int t2,
  required String network,
}) => RustLib.instance.api.crateApiSwapZwapZwapDeriveZ2BMaterial(
  seedHex: seedHex,
  swapId: swapId,
  solverAkSec1: solverAkSec1,
  solverNskLe: solverNskLe,
  solverHB: solverHB,
  solverRefundPubkey: solverRefundPubkey,
  solverSwapHash: solverSwapHash,
  t1: t1,
  t2: t2,
  network: network,
);

/// Build + sign the z2b BTC branch-1 claim spend of the solver-funded lock,
/// returning the raw tx hex (for esplora `POST /tx` broadcast) + its txid. The
/// user's claim private key and joint scalar `k_be` are re-derived from
/// `(seed, swap_id)` in-Rust (never round-tripped through Dart). `swap_secret`
/// is the value the solver revealed (from the recover snapshot).
Future<ZwapSignedBtcTx> zwapSignZ2BBtcClaimTx({
  required String seedHex,
  required String swapId,
  required String lockTxid,
  required int lockVout,
  required BigInt lockValueSat,
  required String witnessScriptHex,
  required String swapSecretHex,
  required String destSpkHex,
  required BigInt feeSat,
}) => RustLib.instance.api.crateApiSwapZwapZwapSignZ2BBtcClaimTx(
  seedHex: seedHex,
  swapId: swapId,
  lockTxid: lockTxid,
  lockVout: lockVout,
  lockValueSat: lockValueSat,
  witnessScriptHex: witnessScriptHex,
  swapSecretHex: swapSecretHex,
  destSpkHex: destSpkHex,
  feeSat: feeSat,
);

/// Assemble the z2e `feMaterial` inputs for `swap_id`. Reuses the e2z DLEq
/// material; adds `claim_pubkey` (`deriveBtcClaimKeypair`) for the `refundPubkey`
/// field and `k_be` (the single-scalar EVM claim key, also the DLEq input).
Future<ZwapZ2eOrderInputs> zwapZ2EOrderInputs({
  required String seedHex,
  required String swapId,
}) => RustLib.instance.api.crateApiSwapZwapZwapZ2EOrderInputs(
  seedHex: seedHex,
  swapId: swapId,
);

/// Derive the z2e EVM lock + joint-UA material. `token_hex` is the zero address
/// for native ETH (z2e) or the ERC-20 contract (z2erc20). `contract_hex` is the
/// singleton `ZwapHtlc`. `recipient_evm_addr`/`solver_evm_addr` (20-byte hex)
/// come from the recover snapshot; both bind into the slot id.
Future<ZwapZ2eMaterial> zwapDeriveZ2EMaterial({
  required String seedHex,
  required String swapId,
  required String solverAkSec1,
  required String solverNskLe,
  required String solverLockPubkey,
  required String solverRefundPubkey,
  required String solverHB,
  required String solverSwapHash,
  required String recipientEvmAddr,
  required String solverEvmAddr,
  required BigInt timelock,
  required BigInt chainId,
  required String contractHex,
  required String tokenHex,
  required String network,
}) => RustLib.instance.api.crateApiSwapZwapZwapDeriveZ2EMaterial(
  seedHex: seedHex,
  swapId: swapId,
  solverAkSec1: solverAkSec1,
  solverNskLe: solverNskLe,
  solverLockPubkey: solverLockPubkey,
  solverRefundPubkey: solverRefundPubkey,
  solverHB: solverHB,
  solverSwapHash: solverSwapHash,
  recipientEvmAddr: recipientEvmAddr,
  solverEvmAddr: solverEvmAddr,
  timelock: timelock,
  chainId: chainId,
  contractHex: contractHex,
  tokenHex: tokenHex,
  network: network,
);

/// z2e Phase0 refund pre-share: sign the `refund_to_initiator` digest with the
/// user's per-swap key (`deriveBtcClaimKeypair`, whose address == the slot's
/// `br_B`). The solver assembles its t1 inactivity refund with this + its own
/// adaptor; posting it never cooperates live. Returns the 65-byte sig (hex).
Future<String> zwapZ2ERefundSigB({
  required String seedHex,
  required String swapId,
  required String refundToInitiatorDigestHex,
}) => RustLib.instance.api.crateApiSwapZwapZwapZ2ERefundSigB(
  seedHex: seedHex,
  swapId: swapId,
  refundToInitiatorDigestHex: refundToInitiatorDigestHex,
);

Future<ZwapZ2eClaimSigs> zwapZ2EClaimSigs({
  required String seedHex,
  required String swapId,
  required String adaptorHex,
  required String claimBuyDigestHex,
  required String solverClaimAddrHex,
}) => RustLib.instance.api.crateApiSwapZwapZwapZ2EClaimSigs(
  seedHex: seedHex,
  swapId: swapId,
  adaptorHex: adaptorHex,
  claimBuyDigestHex: claimBuyDigestHex,
  solverClaimAddrHex: solverClaimAddrHex,
);

/// Decode a segwit BTC address (bech32 v0 p2wpkh/p2wsh, bech32m v1 p2tr) into
/// its `scriptPubKey` hex — the z2b claim payout target the user types in.
Future<String> zwapBtcAddressToSpkHex({required String address}) => RustLib
    .instance
    .api
    .crateApiSwapZwapZwapBtcAddressToSpkHex(address: address);

/// Decode a unified address (`u1…`/`uregtest1…`/`utest1…`) and return its
/// Orchard receiver as 43-byte raw hex — the `dest_raw_address` the joint-note
/// sweep (`zwap_orchard_spend`) pays to. Errors if the UA has no Orchard
/// receiver.
Future<String> zwapUnifiedToOrchardRawHex({required String unifiedAddress}) =>
    RustLib.instance.api.crateApiSwapZwapZwapUnifiedToOrchardRawHex(
      unifiedAddress: unifiedAddress,
    );

/// Build the e2z/z2e `claim_buy` ADAPTOR signature (serialized hex): sign the
/// EIP-191-wrapped `claim_buy_digest` with the wallet's own `k_be` (the buy
/// key, single-scalar reuse), encrypted under the solver's `encryption_point`
/// (its DLEq secp pubkey = the solver `lockPubkey`). The solver completes it
/// with its own `k_be` at claim → reveals `k_solver`, which the wallet then
/// recovers to sweep the joint note. Mirrors the SDK `buildClaimBuyAdaptor`.
Future<String> zwapBuildClaimBuyAdaptor({
  required String seedHex,
  required String swapId,
  required String encryptionPointHex,
  required String claimBuyDigestHex,
}) => RustLib.instance.api.crateApiSwapZwapZwapBuildClaimBuyAdaptor(
  seedHex: seedHex,
  swapId: swapId,
  encryptionPointHex: encryptionPointHex,
  claimBuyDigestHex: claimBuyDigestHex,
);

/// e2z/z2e sweep recovery: recover the solver's joint-note scalar `k_b`
/// (BE hex) from its on-chain `claim_buy` signature (compact `r‖s`, hex) plus
/// the Phase0 adaptor (serialized hex), selecting the s-malleability candidate
/// whose secp pubkey equals `expected_secp_pubkey_hex` (the solver `lockPubkey`
/// = `k_solver·G_secp`). Errors (never guesses) if neither candidate matches.
Future<String> zwapRecoverKFromClaimSig({
  required String adaptorHex,
  required String onchainSigHex,
  required String expectedSecpPubkeyHex,
}) => RustLib.instance.api.crateApiSwapZwapZwapRecoverKFromClaimSig(
  adaptorHex: adaptorHex,
  onchainSigHex: onchainSigHex,
  expectedSecpPubkeyHex: expectedSecpPubkeyHex,
);

/// Build the e2z/z2e DLEq feMaterial for `swap_id`. Self-verifies the proof
/// (the matcher re-runs `verify`; committing an unverifiable proof would strand
/// a funded swap) and asserts the DLEq Pallas point equals the derived `ak_a`.
Future<ZwapDleqMaterial> zwapE2ZDleqMaterial({
  required String seedHex,
  required String swapId,
}) => RustLib.instance.api.crateApiSwapZwapZwapE2ZDleqMaterial(
  seedHex: seedHex,
  swapId: swapId,
);

/// Flat, FRB-friendly result of [`zwap_derive_b2z_material`].
class ZwapB2zMaterial {
  /// Bech32 P2WSH address the user funds with BTC (their lock deposit).
  final String btcLockAddress;

  /// Lock witnessScript (hex) — retained for the later spend/refund path.
  final String witnessScriptHex;

  /// Joint Orchard unified address the solver funds and the user sweeps.
  final String jointZecAddress;

  /// Joint Orchard UFVK (`uview…`) — view-only key to scan the joint UA.
  final String jointZecUfvk;

  /// Joint Orchard `nk`/`rivk` (32-byte hex) — required (with the reconstructed
  /// `ask`) to build the joint-note sweep. These are the raw values, NOT the
  /// UFVK string.
  final String jointZecNkHex;
  final String jointZecRivkHex;

  /// Joint `ak`/`ivk`/`diversifier` (hex) — to trial-decrypt the note locally.
  final String jointZecAkHex;
  final String jointZecIvkHex;
  final String jointZecDiversifierHex;

  /// `swap_hash = SHA256(secret)`, hex (lock branch-1 commitment).
  final String swapHashHex;

  /// `h_a = SHA256(k_a)`, hex (lock refund-branch commitment).
  final String hAHex;

  const ZwapB2zMaterial({
    required this.btcLockAddress,
    required this.witnessScriptHex,
    required this.jointZecAddress,
    required this.jointZecUfvk,
    required this.jointZecNkHex,
    required this.jointZecRivkHex,
    required this.jointZecAkHex,
    required this.jointZecIvkHex,
    required this.jointZecDiversifierHex,
    required this.swapHashHex,
    required this.hAHex,
  });

  @override
  int get hashCode =>
      btcLockAddress.hashCode ^
      witnessScriptHex.hashCode ^
      jointZecAddress.hashCode ^
      jointZecUfvk.hashCode ^
      jointZecNkHex.hashCode ^
      jointZecRivkHex.hashCode ^
      jointZecAkHex.hashCode ^
      jointZecIvkHex.hashCode ^
      jointZecDiversifierHex.hashCode ^
      swapHashHex.hashCode ^
      hAHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZwapB2zMaterial &&
          runtimeType == other.runtimeType &&
          btcLockAddress == other.btcLockAddress &&
          witnessScriptHex == other.witnessScriptHex &&
          jointZecAddress == other.jointZecAddress &&
          jointZecUfvk == other.jointZecUfvk &&
          jointZecNkHex == other.jointZecNkHex &&
          jointZecRivkHex == other.jointZecRivkHex &&
          jointZecAkHex == other.jointZecAkHex &&
          jointZecIvkHex == other.jointZecIvkHex &&
          jointZecDiversifierHex == other.jointZecDiversifierHex &&
          swapHashHex == other.swapHashHex &&
          hAHex == other.hAHex;
}

/// The b2z order `feMaterial` fields the wallet owns, matching the SDK
/// `buildFeMaterialAsync` exactly — everything except the hashbind proof, which
/// the caller produces by feeding [`Self::k_be_hex`] to the ProveKit prover.
///
/// `k_be_hex` is the raw spend-auth scalar `k_a` (BE) — the prover's input. It
/// is the one secret that must reach the prover; on-device proving keeps it in
/// Rust, while a regtest HTTP prover trades that for test convenience.
class ZwapB2zOrderInputs {
  final String hA;
  final String swapHash;
  final String akA;
  final String nskA;
  final String lockPubkey;
  final String refundPubkey;
  final String kBeHex;

  const ZwapB2zOrderInputs({
    required this.hA,
    required this.swapHash,
    required this.akA,
    required this.nskA,
    required this.lockPubkey,
    required this.refundPubkey,
    required this.kBeHex,
  });

  @override
  int get hashCode =>
      hA.hashCode ^
      swapHash.hashCode ^
      akA.hashCode ^
      nskA.hashCode ^
      lockPubkey.hashCode ^
      refundPubkey.hashCode ^
      kBeHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZwapB2zOrderInputs &&
          runtimeType == other.runtimeType &&
          hA == other.hA &&
          swapHash == other.swapHash &&
          akA == other.akA &&
          nskA == other.nskA &&
          lockPubkey == other.lockPubkey &&
          refundPubkey == other.refundPubkey &&
          kBeHex == other.kBeHex;
}

/// The e2z/z2e FE proof material — the Pallas DLEq that EVM-leg swaps require
/// (instead of the b2z hashbind SNARK). Binds `ak_a` (Orchard SpendAuth point,
/// = the FE's lock pubkey on Pallas) to the secp lock pubkey `k_a·G_secp`.
class ZwapDleqMaterial {
  /// The secp lock pubkey `k_a·G_secp` (33-byte compressed hex) — the
  /// feMaterial `lockPubkey` for `proofKind='dleq'`.
  final String lockPubkeySecpHex;

  /// The serialized Pallas DLEq proof (hex) — the feMaterial `hashbindProof`.
  final String dleqProofHex;

  const ZwapDleqMaterial({
    required this.lockPubkeySecpHex,
    required this.dleqProofHex,
  });

  @override
  int get hashCode => lockPubkeySecpHex.hashCode ^ dleqProofHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZwapDleqMaterial &&
          runtimeType == other.runtimeType &&
          lockPubkeySecpHex == other.lockPubkeySecpHex &&
          dleqProofHex == other.dleqProofHex;
}

/// Flat FRB result of [`zwap_derive_e2z_proxy_material`].
class ZwapE2zMaterial {
  /// CREATE2 proxy deposit address (0x-hex) the user funds with ETH.
  final String depositAddress;

  /// The proxy CREATE2 salt (0x-hex).
  final String saltHex;
  final String claimBuyDigest;
  final String refundToInitiatorDigest;
  final String refundAfterClaimDigest;

  /// Joint Orchard unified address the user sweeps.
  final String jointZecAddress;
  final String jointZecUfvk;

  /// Joint Orchard `nk`/`rivk` (32-byte hex) for the sweep.
  final String jointZecNkHex;
  final String jointZecRivkHex;

  /// Joint `ak`/`ivk`/`diversifier` (hex) — for local trial-decryption.
  final String jointZecAkHex;
  final String jointZecIvkHex;
  final String jointZecDiversifierHex;
  final String swapHashHex;

  /// Canonical `proxyTerms` JSON to post to the orderbook at Phase0.
  final String proxyTermsJson;

  const ZwapE2zMaterial({
    required this.depositAddress,
    required this.saltHex,
    required this.claimBuyDigest,
    required this.refundToInitiatorDigest,
    required this.refundAfterClaimDigest,
    required this.jointZecAddress,
    required this.jointZecUfvk,
    required this.jointZecNkHex,
    required this.jointZecRivkHex,
    required this.jointZecAkHex,
    required this.jointZecIvkHex,
    required this.jointZecDiversifierHex,
    required this.swapHashHex,
    required this.proxyTermsJson,
  });

  @override
  int get hashCode =>
      depositAddress.hashCode ^
      saltHex.hashCode ^
      claimBuyDigest.hashCode ^
      refundToInitiatorDigest.hashCode ^
      refundAfterClaimDigest.hashCode ^
      jointZecAddress.hashCode ^
      jointZecUfvk.hashCode ^
      jointZecNkHex.hashCode ^
      jointZecRivkHex.hashCode ^
      jointZecAkHex.hashCode ^
      jointZecIvkHex.hashCode ^
      jointZecDiversifierHex.hashCode ^
      swapHashHex.hashCode ^
      proxyTermsJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZwapE2zMaterial &&
          runtimeType == other.runtimeType &&
          depositAddress == other.depositAddress &&
          saltHex == other.saltHex &&
          claimBuyDigest == other.claimBuyDigest &&
          refundToInitiatorDigest == other.refundToInitiatorDigest &&
          refundAfterClaimDigest == other.refundAfterClaimDigest &&
          jointZecAddress == other.jointZecAddress &&
          jointZecUfvk == other.jointZecUfvk &&
          jointZecNkHex == other.jointZecNkHex &&
          jointZecRivkHex == other.jointZecRivkHex &&
          jointZecAkHex == other.jointZecAkHex &&
          jointZecIvkHex == other.jointZecIvkHex &&
          jointZecDiversifierHex == other.jointZecDiversifierHex &&
          swapHashHex == other.swapHashHex &&
          proxyTermsJson == other.proxyTermsJson;
}

/// The wallet's own public Orchard half + hashlock commitment for `swap_id` —
/// what the wallet reports to the orderbook at Phase0 so the solver can derive
/// and verify the same joint UA. Hex-encoded.
class ZwapInitiatorHalf {
  final String akSec1;
  final String nskLe;

  /// `h_a = SHA256(k_a)` — published; `k_a` itself stays in the wallet.
  final String hAHex;

  /// `swap_hash = SHA256(secret)` — the lock's branch-1 commitment.
  final String swapHashHex;

  const ZwapInitiatorHalf({
    required this.akSec1,
    required this.nskLe,
    required this.hAHex,
    required this.swapHashHex,
  });

  @override
  int get hashCode =>
      akSec1.hashCode ^ nskLe.hashCode ^ hAHex.hashCode ^ swapHashHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZwapInitiatorHalf &&
          runtimeType == other.runtimeType &&
          akSec1 == other.akSec1 &&
          nskLe == other.nskLe &&
          hAHex == other.hAHex &&
          swapHashHex == other.swapHashHex;
}

/// Flat, FRB-friendly signed-tx result.
class ZwapSignedBtcTx {
  final String rawTxHex;
  final String txid;

  const ZwapSignedBtcTx({required this.rawTxHex, required this.txid});

  @override
  int get hashCode => rawTxHex.hashCode ^ txid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZwapSignedBtcTx &&
          runtimeType == other.runtimeType &&
          rawTxHex == other.rawTxHex &&
          txid == other.txid;
}

/// Flat, FRB-friendly result of [`zwap_derive_z2b_material`].
class ZwapZ2bMaterial {
  final String btcLockAddress;
  final String witnessScriptHex;
  final String claimPubkeyHex;
  final String jointZecAddress;
  final String jointZecUfvk;
  final String jointZecNkHex;
  final String jointZecRivkHex;
  final String jointZecAkHex;
  final String jointZecIvkHex;
  final String jointZecDiversifierHex;
  final String swapHashHex;
  final String hBHex;

  const ZwapZ2bMaterial({
    required this.btcLockAddress,
    required this.witnessScriptHex,
    required this.claimPubkeyHex,
    required this.jointZecAddress,
    required this.jointZecUfvk,
    required this.jointZecNkHex,
    required this.jointZecRivkHex,
    required this.jointZecAkHex,
    required this.jointZecIvkHex,
    required this.jointZecDiversifierHex,
    required this.swapHashHex,
    required this.hBHex,
  });

  @override
  int get hashCode =>
      btcLockAddress.hashCode ^
      witnessScriptHex.hashCode ^
      claimPubkeyHex.hashCode ^
      jointZecAddress.hashCode ^
      jointZecUfvk.hashCode ^
      jointZecNkHex.hashCode ^
      jointZecRivkHex.hashCode ^
      jointZecAkHex.hashCode ^
      jointZecIvkHex.hashCode ^
      jointZecDiversifierHex.hashCode ^
      swapHashHex.hashCode ^
      hBHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZwapZ2bMaterial &&
          runtimeType == other.runtimeType &&
          btcLockAddress == other.btcLockAddress &&
          witnessScriptHex == other.witnessScriptHex &&
          claimPubkeyHex == other.claimPubkeyHex &&
          jointZecAddress == other.jointZecAddress &&
          jointZecUfvk == other.jointZecUfvk &&
          jointZecNkHex == other.jointZecNkHex &&
          jointZecRivkHex == other.jointZecRivkHex &&
          jointZecAkHex == other.jointZecAkHex &&
          jointZecIvkHex == other.jointZecIvkHex &&
          jointZecDiversifierHex == other.jointZecDiversifierHex &&
          swapHashHex == other.swapHashHex &&
          hBHex == other.hBHex;
}

/// The z2b order `feMaterial` fields the wallet owns. Same shape as the b2z
/// inputs EXCEPT: z2b has NO `swap_hash` (the solver owns the secret), and the
/// FE-material `refundPubkey` field carries the user's per-swap BTC CLAIM pubkey
/// (`b_b`), not a refund key. `k_be_hex` is the hashbind prover input.
class ZwapZ2bOrderInputs {
  final String hA;
  final String akA;
  final String nskA;
  final String lockPubkey;

  /// The user's per-swap BTC claim pubkey `b_b` — posted as `refundPubkey`.
  final String claimPubkey;
  final String kBeHex;

  const ZwapZ2bOrderInputs({
    required this.hA,
    required this.akA,
    required this.nskA,
    required this.lockPubkey,
    required this.claimPubkey,
    required this.kBeHex,
  });

  @override
  int get hashCode =>
      hA.hashCode ^
      akA.hashCode ^
      nskA.hashCode ^
      lockPubkey.hashCode ^
      claimPubkey.hashCode ^
      kBeHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZwapZ2bOrderInputs &&
          runtimeType == other.runtimeType &&
          hA == other.hA &&
          akA == other.akA &&
          nskA == other.nskA &&
          lockPubkey == other.lockPubkey &&
          claimPubkey == other.claimPubkey &&
          kBeHex == other.kBeHex;
}

/// z2e claim sigs: complete the solver's `claim_buy` adaptor with the user's
/// `k_be` (→ sig_a recovering to `solver_claim_addr`) and sign the digest with
/// `k_be` (→ sig_b, the user's own). Returns both 65-byte sigs (hex); the caller
/// relays them + the preimage to the eth-relayer's `claim_buy`.
class ZwapZ2eClaimSigs {
  final String sigAHex;
  final String sigBHex;

  const ZwapZ2eClaimSigs({required this.sigAHex, required this.sigBHex});

  @override
  int get hashCode => sigAHex.hashCode ^ sigBHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZwapZ2eClaimSigs &&
          runtimeType == other.runtimeType &&
          sigAHex == other.sigAHex &&
          sigBHex == other.sigBHex;
}

/// Flat, FRB-friendly result of [`zwap_derive_z2e_material`].
class ZwapZ2eMaterial {
  final String jointZecAddress;
  final String jointZecUfvk;
  final String jointZecNkHex;
  final String jointZecRivkHex;
  final String jointZecAkHex;
  final String jointZecIvkHex;
  final String jointZecDiversifierHex;
  final String evmSlotIdHex;
  final String claimBuyDigestHex;
  final String refundToInitiatorDigestHex;
  final String solverClaimAddrHex;
  final String swapHashHex;
  final String hBHex;

  const ZwapZ2eMaterial({
    required this.jointZecAddress,
    required this.jointZecUfvk,
    required this.jointZecNkHex,
    required this.jointZecRivkHex,
    required this.jointZecAkHex,
    required this.jointZecIvkHex,
    required this.jointZecDiversifierHex,
    required this.evmSlotIdHex,
    required this.claimBuyDigestHex,
    required this.refundToInitiatorDigestHex,
    required this.solverClaimAddrHex,
    required this.swapHashHex,
    required this.hBHex,
  });

  @override
  int get hashCode =>
      jointZecAddress.hashCode ^
      jointZecUfvk.hashCode ^
      jointZecNkHex.hashCode ^
      jointZecRivkHex.hashCode ^
      jointZecAkHex.hashCode ^
      jointZecIvkHex.hashCode ^
      jointZecDiversifierHex.hashCode ^
      evmSlotIdHex.hashCode ^
      claimBuyDigestHex.hashCode ^
      refundToInitiatorDigestHex.hashCode ^
      solverClaimAddrHex.hashCode ^
      swapHashHex.hashCode ^
      hBHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZwapZ2eMaterial &&
          runtimeType == other.runtimeType &&
          jointZecAddress == other.jointZecAddress &&
          jointZecUfvk == other.jointZecUfvk &&
          jointZecNkHex == other.jointZecNkHex &&
          jointZecRivkHex == other.jointZecRivkHex &&
          jointZecAkHex == other.jointZecAkHex &&
          jointZecIvkHex == other.jointZecIvkHex &&
          jointZecDiversifierHex == other.jointZecDiversifierHex &&
          evmSlotIdHex == other.evmSlotIdHex &&
          claimBuyDigestHex == other.claimBuyDigestHex &&
          refundToInitiatorDigestHex == other.refundToInitiatorDigestHex &&
          solverClaimAddrHex == other.solverClaimAddrHex &&
          swapHashHex == other.swapHashHex &&
          hBHex == other.hBHex;
}

/// The z2e order `feMaterial` inputs. EVM legs use a Pallas DLEq (not hashbind):
/// `lock_pubkey`+`dleq_proof` are the DLEq material; `claim_pubkey` (the user's
/// per-swap key) is posted as `refundPubkey`; NO `swapHash` (solver-owned).
class ZwapZ2eOrderInputs {
  final String hA;
  final String akA;
  final String nskA;
  final String lockPubkey;
  final String dleqProof;
  final String claimPubkey;
  final String kBeHex;

  const ZwapZ2eOrderInputs({
    required this.hA,
    required this.akA,
    required this.nskA,
    required this.lockPubkey,
    required this.dleqProof,
    required this.claimPubkey,
    required this.kBeHex,
  });

  @override
  int get hashCode =>
      hA.hashCode ^
      akA.hashCode ^
      nskA.hashCode ^
      lockPubkey.hashCode ^
      dleqProof.hashCode ^
      claimPubkey.hashCode ^
      kBeHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZwapZ2eOrderInputs &&
          runtimeType == other.runtimeType &&
          hA == other.hA &&
          akA == other.akA &&
          nskA == other.nskA &&
          lockPubkey == other.lockPubkey &&
          dleqProof == other.dleqProof &&
          claimPubkey == other.claimPubkey &&
          kBeHex == other.kBeHex;
}
