// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CSyncProgress`

/// Run full sync from C (Swift). Blocks until complete or cancelled.
/// Returns 0 on success, 1 on error.
Future<int> zcashRunFullSync({
  required ConstCChar dbPath,
  required ConstCChar cachePath,
  required ConstCChar lightwalletdUrl,
  required ConstCChar network,
  required ExternCFnCSyncProgress progressCallback,
}) => RustLib.instance.api.crateApiSyncFfiZcashRunFullSync(
  dbPath: dbPath,
  cachePath: cachePath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  progressCallback: progressCallback,
);

/// Cancel a running C FFI sync.
Future<void> zcashCancelSync() =>
    RustLib.instance.api.crateApiSyncFfiZcashCancelSync();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<* const c_char>>
abstract class ConstCChar implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<extern "C" fn (CSyncProgress)>>
abstract class ExternCFnCSyncProgress implements RustOpaqueInterface {}
