// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/zcash_voting/config.dart';
import '../third_party/zcash_voting/delegate.dart';
import '../third_party/zcash_voting/share_policy.dart';
import '../third_party/zcash_voting/wire.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'voting.dart';

// These functions are ignored because they are not marked as `pub`: `advance`, `delegation_inputs`, `internal`, `invalid_input`, `pipeline`, `storage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Opens a session bound to `ctx`'s account and round.
///
/// `stored_hotkey_secret` is required only for sessions that cast votes.
/// Chain and helper traffic use the wallet's network route; PIR and vote-tree
/// traffic use the SDK's direct transport.
VotingRoundSession openVotingRoundSession({
  required ApiVotingRoundContext ctx,
  required List<String> chainEndpoints,
  required List<String> pirServerUrls,
  required List<ApiProposalRosterEntry> proposals,
  Uint8List? storedHotkeySecret,
  required BigInt operationEpoch,
}) => RustLib.instance.api.crateApiVotingSessionOpenVotingRoundSession(
  ctx: ctx,
  chainEndpoints: chainEndpoints,
  pirServerUrls: pirServerUrls,
  proposals: proposals,
  storedHotkeySecret: storedHotkeySecret,
  operationEpoch: operationEpoch,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VotingRoundSession>>
abstract class VotingRoundSession implements RustOpaqueInterface {
  /// Runs the first planned step, streaming progress then one result.
  Stream<ApiRoundStepEvent> advanceNext({
    required ApiRoundHostContext host,
    ApiDelegationSignerInput? signer,
  });

  /// Runs one planned step, streaming progress then one result.
  Stream<ApiRoundStepEvent> advanceStep({
    required NextStepView step,
    required ApiRoundHostContext host,
    ApiDelegationSignerInput? signer,
  });

  /// Cancellation handle for one helper-share tracking pass on this round.
  ///
  /// Tracking passes are cancelled by the destructive drain independently
  /// of the session's own control, so a background drain never aborts a
  /// foreground cast.
  VotingShareTrackingPassHandle beginShareTrackingPass();

  /// Cancels every step in flight or queued on this session.
  void cancel();

  /// Builds redacted Keystone signing requests for the given bundles.
  Future<List<KeystoneSigningRequest>> keystoneSigningRequests({
    required List<int> bundleIndices,
  });

  /// Plans the round from durable state.
  Future<RoundPlanView> plan();

  /// Records ballot decisions against the bound roster and re-plans.
  Future<RoundPlanView> setBallotIntents({
    required List<ApiBallotIntent> intents,
  });

  void setOperationEpoch({required BigInt operationEpoch});
}

/// One ballot decision to record before casting.
class ApiBallotIntent {
  final int proposalId;

  /// `true` records `Skipped`; otherwise `choice` is required.
  final bool skipped;
  final int? choice;

  const ApiBallotIntent({
    required this.proposalId,
    required this.skipped,
    this.choice,
  });

  @override
  int get hashCode => proposalId.hashCode ^ skipped.hashCode ^ choice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiBallotIntent &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          skipped == other.skipped &&
          choice == other.choice;
}

class ApiDelegationSignerInput {
  final ApiDelegationSignerKind kind;
  final String? mnemonic;
  final Uint8List? keystoneSig;
  final Uint8List? keystoneSighash;

  const ApiDelegationSignerInput({
    required this.kind,
    this.mnemonic,
    this.keystoneSig,
    this.keystoneSighash,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      mnemonic.hashCode ^
      keystoneSig.hashCode ^
      keystoneSighash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDelegationSignerInput &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          mnemonic == other.mnemonic &&
          keystoneSig == other.keystoneSig &&
          keystoneSighash == other.keystoneSighash;
}

/// How a delegation step signs.
enum ApiDelegationSignerKind {
  /// Software account: `mnemonic` must be set.
  mnemonic,

  /// Keystone account: use the signature stored for the bundle.
  keystoneStored,

  /// Keystone account: use the provided signature bytes.
  keystoneProvided,
}

/// One proposal from the authenticated round configuration.
class ApiProposalRosterEntry {
  final int proposalId;
  final int numOptions;

  const ApiProposalRosterEntry({
    required this.proposalId,
    required this.numOptions,
  });

  @override
  int get hashCode => proposalId.hashCode ^ numOptions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiProposalRosterEntry &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          numOptions == other.numOptions;
}

/// Host inputs that change per step call.
class ApiRoundHostContext {
  /// Complete current helper fleet, already mapped to transport URLs.
  final List<String> configuredHelperUrls;
  final BigInt nowSeconds;
  final BigInt? ceremonyStartSeconds;
  final BigInt? voteEndTimeSeconds;

  /// Vote-tree node URLs tried in order by cast-vote steps.
  final List<String> voteTreeNodeUrls;
  final int maxProofConcurrency;

  const ApiRoundHostContext({
    required this.configuredHelperUrls,
    required this.nowSeconds,
    this.ceremonyStartSeconds,
    this.voteEndTimeSeconds,
    required this.voteTreeNodeUrls,
    required this.maxProofConcurrency,
  });

  @override
  int get hashCode =>
      configuredHelperUrls.hashCode ^
      nowSeconds.hashCode ^
      ceremonyStartSeconds.hashCode ^
      voteEndTimeSeconds.hashCode ^
      voteTreeNodeUrls.hashCode ^
      maxProofConcurrency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiRoundHostContext &&
          runtimeType == other.runtimeType &&
          configuredHelperUrls == other.configuredHelperUrls &&
          nowSeconds == other.nowSeconds &&
          ceremonyStartSeconds == other.ceremonyStartSeconds &&
          voteEndTimeSeconds == other.voteEndTimeSeconds &&
          voteTreeNodeUrls == other.voteTreeNodeUrls &&
          maxProofConcurrency == other.maxProofConcurrency;
}

/// One event of a streamed step: progress while it runs, then one result.
class ApiRoundStepEvent {
  final ApiRoundStepEventKind kind;
  final RoundStepProgressView? progress;
  final RoundStepOutcomeView? outcome;
  final RoundStepFailureView? failure;

  const ApiRoundStepEvent({
    required this.kind,
    this.progress,
    this.outcome,
    this.failure,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ progress.hashCode ^ outcome.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiRoundStepEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          progress == other.progress &&
          outcome == other.outcome &&
          failure == other.failure;
}

enum ApiRoundStepEventKind { progress, result }
