// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/zcash_voting/config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

/// Resolve static + dynamic voting config via a wallet-owned fetch callback.
///
/// Rust validates config authenticity and computes config switch semantics.
/// The wallet keeps transport ownership via `fetch_bytes`.
Future<VotingConfigResolution> resolveVotingConfig({
  required String source,
  ResolvedVotingConfig? previous,
  required FutureOr<Uint8List> Function(String) fetchBytes,
}) => RustLib.instance.api.crateApiVotingConfigResolveVotingConfig(
  source: source,
  previous: previous,
  fetchBytes: fetchBytes,
);

class VotingConfigResolution {
  final ResolvedVotingConfig config;
  final ConfigSwitchKind switchKind;

  const VotingConfigResolution({
    required this.config,
    required this.switchKind,
  });

  @override
  int get hashCode => config.hashCode ^ switchKind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VotingConfigResolution &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          switchKind == other.switchKind;
}
