// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `catch`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

Future<void> prepareVotingRound({
  required String dbPath,
  required String walletId,
  required ApiVotingRoundParams roundParams,
  String? sessionJson,
}) => RustLib.instance.api.crateApiVotingPrepareVotingRound(
  dbPath: dbPath,
  walletId: walletId,
  roundParams: roundParams,
  sessionJson: sessionJson,
);

Future<int> getBundleCount({
  required String dbPath,
  required String walletId,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetBundleCount(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
);

Future<ApiVotingBundleSetupResult> setupDelegationBundles({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required ApiVotingRoundParams roundParams,
  required String roundName,
  String? sessionJson,
  required String accountUuid,
}) => RustLib.instance.api.crateApiVotingSetupDelegationBundles(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  roundParams: roundParams,
  roundName: roundName,
  sessionJson: sessionJson,
  accountUuid: accountUuid,
);

Future<ApiSignedDelegation> buildAndProveDelegationBundle({
  required String dbPath,
  required String lightwalletdUrl,
  required String pirServerUrl,
  required String network,
  required ApiVotingRoundParams roundParams,
  required String roundName,
  String? sessionJson,
  required String accountUuid,
  required List<int> seedBytes,
  required int bundleIndex,
}) => RustLib.instance.api.crateApiVotingBuildAndProveDelegationBundle(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  pirServerUrl: pirServerUrl,
  network: network,
  roundParams: roundParams,
  roundName: roundName,
  sessionJson: sessionJson,
  accountUuid: accountUuid,
  seedBytes: seedBytes,
  bundleIndex: bundleIndex,
);

Future<void> storeDelegationTxHash({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required String txHash,
}) => RustLib.instance.api.crateApiVotingStoreDelegationTxHash(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  txHash: txHash,
);

Future<String?> getDelegationTxHash({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
}) => RustLib.instance.api.crateApiVotingGetDelegationTxHash(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
);

Future<int> deleteSkippedBundles({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int keepCount,
}) => RustLib.instance.api.crateApiVotingDeleteSkippedBundles(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  keepCount: keepCount,
);

class ApiSignedDelegation {
  final Uint8List pcztBytes;
  final String txidHex;
  final String status;
  final String? message;
  final BigInt eligibleWeightZatoshi;
  final BigInt delegatedWeightZatoshi;
  final int bundleCount;
  final int bundleIndex;

  const ApiSignedDelegation({
    required this.pcztBytes,
    required this.txidHex,
    required this.status,
    this.message,
    required this.eligibleWeightZatoshi,
    required this.delegatedWeightZatoshi,
    required this.bundleCount,
    required this.bundleIndex,
  });

  @override
  int get hashCode =>
      pcztBytes.hashCode ^
      txidHex.hashCode ^
      status.hashCode ^
      message.hashCode ^
      eligibleWeightZatoshi.hashCode ^
      delegatedWeightZatoshi.hashCode ^
      bundleCount.hashCode ^
      bundleIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSignedDelegation &&
          runtimeType == other.runtimeType &&
          pcztBytes == other.pcztBytes &&
          txidHex == other.txidHex &&
          status == other.status &&
          message == other.message &&
          eligibleWeightZatoshi == other.eligibleWeightZatoshi &&
          delegatedWeightZatoshi == other.delegatedWeightZatoshi &&
          bundleCount == other.bundleCount &&
          bundleIndex == other.bundleIndex;
}

class ApiVotingBundleSetupResult {
  final int bundleCount;
  final BigInt eligibleWeightZatoshi;

  const ApiVotingBundleSetupResult({
    required this.bundleCount,
    required this.eligibleWeightZatoshi,
  });

  @override
  int get hashCode => bundleCount.hashCode ^ eligibleWeightZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingBundleSetupResult &&
          runtimeType == other.runtimeType &&
          bundleCount == other.bundleCount &&
          eligibleWeightZatoshi == other.eligibleWeightZatoshi;
}

class ApiVotingRoundParams {
  final String voteRoundId;
  final BigInt snapshotHeight;
  final Uint8List eaPk;
  final Uint8List ncRoot;
  final Uint8List nullifierImtRoot;

  const ApiVotingRoundParams({
    required this.voteRoundId,
    required this.snapshotHeight,
    required this.eaPk,
    required this.ncRoot,
    required this.nullifierImtRoot,
  });

  @override
  int get hashCode =>
      voteRoundId.hashCode ^
      snapshotHeight.hashCode ^
      eaPk.hashCode ^
      ncRoot.hashCode ^
      nullifierImtRoot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingRoundParams &&
          runtimeType == other.runtimeType &&
          voteRoundId == other.voteRoundId &&
          snapshotHeight == other.snapshotHeight &&
          eaPk == other.eaPk &&
          ncRoot == other.ncRoot &&
          nullifierImtRoot == other.nullifierImtRoot;
}
