// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/zcash_voting/config.dart';
import '../third_party/zcash_voting/delegate.dart';
import '../third_party/zcash_voting/share_policy.dart';
import '../third_party/zcash_voting/types.dart';
import '../third_party/zcash_voting/vote.dart';
import '../third_party/zcash_voting/wire.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_vote_commitments_result`, `catch`, `delegation_progress_event`, `emit_signed_delegation_round_result`, `emit_signed_vote_result`, `log_sink_closed`, `parse_tx_events_json`, `require_len`, `share_record`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

/// Return the shared last-moment helper-share buffer, in Unix seconds.
BigInt? lastMomentBufferSeconds({
  required BigInt ceremonyStartSeconds,
  required BigInt voteEndTimeSeconds,
}) => RustLib.instance.api.crateApiVotingLastMomentBufferSeconds(
  ceremonyStartSeconds: ceremonyStartSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
);

/// Return true when `now_seconds` is inside the active round's last-moment window.
bool isLastMoment({
  required BigInt nowSeconds,
  required BigInt ceremonyStartSeconds,
  required BigInt voteEndTimeSeconds,
}) => RustLib.instance.api.crateApiVotingIsLastMoment(
  nowSeconds: nowSeconds,
  ceremonyStartSeconds: ceremonyStartSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
);

/// Returns the vote-chain delegation submission body as validated wire JSON.
///
/// Binary fields are base64-encoded here so Dart does not duplicate protocol
/// field names or byte encoding rules.
Future<String> delegationSubmissionWireJson({
  required SignedDelegationPayloadView submission,
}) => RustLib.instance.api.crateApiVotingDelegationSubmissionWireJson(
  submission: submission,
);

/// Returns the vote-chain cast-vote submission body as validated wire JSON.
Future<String> voteCommitmentWireJson({
  required VoteCommitmentWire commitment,
}) => RustLib.instance.api.crateApiVotingVoteCommitmentWireJson(
  commitment: commitment,
);

/// Returns the helper-server encrypted-share submission body as wire JSON.
Future<String> voteShareWireJson({
  required VoteShareWire share,
  BigInt? vcTreePosition,
  required BigInt submitAt,
}) => RustLib.instance.api.crateApiVotingVoteShareWireJson(
  share: share,
  vcTreePosition: vcTreePosition,
  submitAt: submitAt,
);

/// Plan independent helper-share timing and randomized helper targets.
///
/// This mirrors the zcash-swift-wallet-sdk wrapper around
/// `zcash_voting::share_policy::plan_share_submissions`, with Rust drawing the
/// policy-sized entropy from the OS CSPRNG before returning FRB-safe plans.
///
/// # Errors
///
/// Returns an error if `share_count` does not fit `usize`, entropy generation
/// fails, or crate policy rejects the supplied timing/server inputs.
Future<List<ShareSubmissionPlan>> planShareSubmissions({
  required int shareCount,
  required List<String> serverUrls,
  required BigInt nowSeconds,
  required BigInt voteEndTimeSeconds,
  BigInt? lastMomentBufferSeconds,
  required bool singleShare,
}) => RustLib.instance.api.crateApiVotingPlanShareSubmissions(
  shareCount: shareCount,
  serverUrls: serverUrls,
  nowSeconds: nowSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
  lastMomentBufferSeconds: lastMomentBufferSeconds,
  singleShare: singleShare,
);

/// Return the crate-owned randomized helper order for one share retry.
Future<List<String>> shareResubmissionServerOrder({
  required List<String> configuredServerUrls,
  required List<String> sentToUrls,
}) => RustLib.instance.api.crateApiVotingShareResubmissionServerOrder(
  configuredServerUrls: configuredServerUrls,
  sentToUrls: sentToUrls,
);

/// Build round params from server metadata while binding trusted `ea_pk`.
///
/// Trust model for the per-round parameters:
///
/// - `ea_pk` (the encryption-authority key votes are encrypted to) is the only
///   field that cannot be independently re-derived by the wallet, so it is
///   always sourced from the authenticated dynamic config and never from the
///   vote server's round response. This call ignores any server-supplied
///   `ea_pk` and substitutes the authenticated value for `round_id`.
/// - `snapshot_height` and `nc_root` are accepted from the server here but are
///   re-verified downstream against the wallet's own lightwalletd-synced
///   Orchard commitment tree: `zcash_voting`'s witness generation
///   (`validate_cached_tree_state_for_round`) requires the synced frontier
///   height and root to match these exactly, so a wrong value fails closed
///   before any vote material is produced.
/// - `nullifier_imt_root` is accepted from the server here but is used
///   downstream as the expected root that PIR nullifier proofs are verified
///   against; a wrong root makes proof verification fail closed rather than
///   enabling a forged non-membership claim.
///
/// In other words, every server-supplied field other than `ea_pk` is
/// cross-checked against an independent source (lightwalletd or PIR proofs)
/// downstream, and `ea_pk` is pinned to authenticated config here. A
/// compromised or stale endpoint therefore cannot steer voting to the wrong
/// authority or roots without being rejected.
Future<VotingRoundParams> trustedVotingRoundParamsFromConfig({
  required ResolvedVotingConfig resolvedConfig,
  required String roundId,
  required BigInt snapshotHeight,
  required List<int> ncRoot,
  required List<int> nullifierImtRoot,
}) => RustLib.instance.api.crateApiVotingTrustedVotingRoundParamsFromConfig(
  resolvedConfig: resolvedConfig,
  roundId: roundId,
  snapshotHeight: snapshotHeight,
  ncRoot: ncRoot,
  nullifierImtRoot: nullifierImtRoot,
);

/// Return share-tracking action flags using `zcash_voting::share_policy`.
///
/// [`SHARE_TRACKING_FLAG_READY`] means the share is ready for status polling.
/// [`SHARE_TRACKING_FLAG_OVERDUE`] means it is overdue and should be retried
/// against helpers that missed the initial submission.
Future<int> shareTrackingFlags({
  required ShareDelegationRecordView share,
  required BigInt nowSeconds,
  BigInt? voteEndTimeSeconds,
}) => RustLib.instance.api.crateApiVotingShareTrackingFlags(
  share: share,
  nowSeconds: nowSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
);

/// Return the next share-tracking delay in seconds using crate policy.
Future<BigInt?> nextShareTrackingDelaySeconds({
  required List<ShareDelegationRecordView> shares,
  required BigInt nowSeconds,
}) => RustLib.instance.api.crateApiVotingNextShareTrackingDelaySeconds(
  shares: shares,
  nowSeconds: nowSeconds,
);

/// Extract and validate one helper-share payload from stored recovery JSON.
///
/// The stored recovery blob is hex-encoded and also contains local-only
/// recovery material. This helper emits only the public wire fields that
/// helper servers accept.
Future<String> recoveredVoteShareWireJson({
  required String commitmentBundleJson,
  required int proposalId,
  required int shareIndex,
  required BigInt vcTreePosition,
  required BigInt submitAt,
}) => RustLib.instance.api.crateApiVotingRecoveredVoteShareWireJson(
  commitmentBundleJson: commitmentBundleJson,
  proposalId: proposalId,
  shareIndex: shareIndex,
  vcTreePosition: vcTreePosition,
  submitAt: submitAt,
);

/// Generate opaque voting hotkey bytes for a local voting account.
///
/// Vizor v2 uses the same random app-owned hotkey model for software and
/// Keystone accounts. The app persists this random per-round hotkey in secure
/// storage and reuses it for delegation setup and vote commitment signing.
Future<Uint8List> generateVotingHotkey({required String network}) =>
    RustLib.instance.api.crateApiVotingGenerateVotingHotkey(network: network);

/// Check whether the account has enough selected notes to vote in this round.
///
/// This selects notes at the round snapshot height and returns the smart-bundle
/// eligibility result without initializing round rows or persisting delegation
/// bundles.
///
/// # Errors
///
/// Returns an error if bundle policy parsing, opening the sidecar DB, note
/// selection, or eligibility calculation fails.
Future<ApiVotingEligibility> checkVotingEligibility({
  required ApiVotingRoundContext ctx,
}) => RustLib.instance.api.crateApiVotingCheckVotingEligibility(ctx: ctx);

/// Persist the complete hotkey-free delegation snapshot tier.
///
/// This is the vote-screen warm-up path. It requires an initialized round and
/// snapshot-selected notes, but no voting hotkey or wallet seed. The normal
/// prove path remains the correctness fallback for missing witnesses or PIR
/// cache rows.
Future<ApiDelegationSnapshotPreparationResult> prepareDelegationSnapshot({
  required ApiVotingRoundContext ctx,
  required String pirServerUrl,
}) => RustLib.instance.api.crateApiVotingPrepareDelegationSnapshot(
  ctx: ctx,
  pirServerUrl: pirServerUrl,
);

/// Read durable delegation snapshot completeness without network access.
Future<ApiDelegationSnapshotStatus> getDelegationSnapshotStatus({
  required String dbPath,
  required String accountUuid,
  required String network,
  required VotingRoundParams roundParams,
}) => RustLib.instance.api.crateApiVotingGetDelegationSnapshotStatus(
  dbPath: dbPath,
  accountUuid: accountUuid,
  network: network,
  roundParams: roundParams,
);

/// Kick off process-lifetime Halo2 proving-key warm-up for voting proofs.
///
/// Safe to call repeatedly; only the first call starts work. Returns
/// immediately so Dart can overlap warm-up with PIR resolve / bundle setup.
void warmVotingProvingCaches() =>
    RustLib.instance.api.crateApiVotingWarmVotingProvingCaches();

/// Warm the bundle-independent PIR proof cache for one account.
///
/// Fetches and caches IMT non-membership proofs for the account's eligible
/// notes at `snapshot_height` against whatever snapshot the PIR endpoint
/// currently serves. Notes are planned with the same whale-protected default
/// bundle policy round setup uses. The library prunes cache rows older than
/// four weeks; `keep_roots` is accepted for FRB compatibility.
///
/// This is a background warm-up path: it needs no hotkey, no round rows, and
/// no bundles, so it can run as soon as the wallet is scanned to the snapshot
/// height. The delegation prove path reads the same cache and still fetches
/// anything missing, so skipping or failing this call only costs latency.
///
/// # Errors
///
/// Returns an error if the network string is invalid, the sidecar cannot be
/// opened, the wallet is not scanned to the snapshot height, note selection
/// fails, the PIR handshake fails, or a fetched proof does not verify.
Future<ApiPirCacheWarmupResult> warmPirProofCache({
  required String dbPath,
  required String accountUuid,
  required String network,
  required String lightwalletdUrl,
  required BigInt snapshotHeight,
  required String pirServerUrl,
  required PirLayout pirLayout,
  required List<Uint8List> keepRoots,
}) => RustLib.instance.api.crateApiVotingWarmPirProofCache(
  dbPath: dbPath,
  accountUuid: accountUuid,
  network: network,
  lightwalletdUrl: lightwalletdUrl,
  snapshotHeight: snapshotHeight,
  pirServerUrl: pirServerUrl,
  pirLayout: pirLayout,
  keepRoots: keepRoots,
);

/// Prepare one software delegation round and stream concurrent bundle proofs.
///
/// Lightwalletd is resolved once. The wallet and round are gathered/prepared
/// once, requested proofs run concurrently on scoped 64 MiB-stack workers, the
/// complete proof batch is persisted atomically, and signatures are assembled
/// before a terminal bundle-index-ordered payload list is emitted.
Stream<ApiDelegationRoundEvent> buildProveAndSignDelegationRoundWithProgress({
  required ApiVotingRoundContext ctx,
  required String mnemonic,
  required List<int> storedHotkeySecret,
  required List<int> bundleIndexes,
}) => RustLib.instance.api
    .crateApiVotingBuildProveAndSignDelegationRoundWithProgress(
      ctx: ctx,
      mnemonic: mnemonic,
      storedHotkeySecret: storedHotkeySecret,
      bundleIndexes: bundleIndexes,
    );

/// Finish hotkey-bound round preparation and return signer-safe PCZTs.
///
/// # Errors
///
/// Returns an error if bundle indexes are empty or duplicated, round input
/// resolution fails, or PCZT construction and redaction for any requested
/// bundle fails.
Future<List<KeystoneSigningRequest>> finishDelegationRoundPreparation({
  required ApiVotingRoundContext ctx,
  required List<int> storedHotkeySecret,
  required List<int> bundleIndexes,
}) => RustLib.instance.api.crateApiVotingFinishDelegationRoundPreparation(
  ctx: ctx,
  storedHotkeySecret: storedHotkeySecret,
  bundleIndexes: bundleIndexes,
);

/// Persist a Keystone signature for one delegation bundle.
///
/// # Errors
///
/// Returns an error if signature lengths are invalid, opening the voting DB
/// fails, or persisting the signature record fails.
Future<void> storeKeystoneSignature({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required List<int> sig,
  required List<int> sighash,
  required List<int> rk,
}) => RustLib.instance.api.crateApiVotingStoreKeystoneSignature(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  sig: sig,
  sighash: sighash,
  rk: rk,
);

/// Atomically persist a batch of Keystone delegation signatures.
///
/// Existing tuples for the same sighash and randomized key are accepted as
/// idempotent retries, even when randomized signing produced different valid
/// signature bytes. A tuple for a different signing context is a conflict, and
/// any validation or database error rolls back the complete batch.
Future<ApiKeystoneSignatureBatchResult> storeKeystoneSignaturesBatch({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required List<ApiKeystoneSignatureInput> signatures,
}) => RustLib.instance.api.crateApiVotingStoreKeystoneSignaturesBatch(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  signatures: signatures,
);

/// Load persisted Keystone signatures for one voting round.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails or signature rows cannot be
/// loaded.
Future<List<KeystoneSignatureRecord>> getKeystoneSignatures({
  required String dbPath,
  required String accountUuid,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetKeystoneSignatures(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Resume a prepared Keystone round and stream concurrent bundle proofs.
///
/// This path performs no lightwalletd/PIR work and never rebuilds signed PCZTs.
/// It validates the durable round against historical wallet notes, captures and
/// proves requested bundles, atomically persists the proof batch, then assembles
/// the externally produced signatures.
Stream<ApiDelegationRoundEvent>
buildProveDelegationRoundWithKeystoneSignaturesWithProgress({
  required ApiVotingRoundContext ctx,
  required List<int> storedHotkeySecret,
  required List<ApiDelegationSignatureInput> signatures,
}) => RustLib.instance.api
    .crateApiVotingBuildProveDelegationRoundWithKeystoneSignaturesWithProgress(
      ctx: ctx,
      storedHotkeySecret: storedHotkeySecret,
      signatures: signatures,
    );

/// Record a submitted delegation transaction hash for one bundle.
///
/// Repeated calls are idempotent only for the same transaction hash.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the bundle key is missing,
/// or the stored hash conflicts with `tx_hash`.
Future<void> markDelegationSubmitted({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required String txHash,
}) => RustLib.instance.api.crateApiVotingMarkDelegationSubmitted(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  txHash: txHash,
);

/// Parse tx events and record a confirmed delegation submission.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the event payload does not
/// match the expected round/type shape, or confirmation state cannot be stored.
Future<DelegationConfirmation> confirmDelegationSubmission({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required String txHash,
  required String eventsJson,
}) => RustLib.instance.api.crateApiVotingConfirmDelegationSubmission(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  txHash: txHash,
  eventsJson: eventsJson,
);

/// Delete bundle rows at or above `keep_count` for partial-bundle recovery.
///
/// Returns the eligible voting weight represented by the retained prefix.
Future<BigInt> deleteSkippedBundles({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int keepCount,
}) => RustLib.instance.api.crateApiVotingDeleteSkippedBundles(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  keepCount: keepCount,
);

/// Sync vote commitment tree state for a voting round.
///
/// Returns the latest synced tree height. The underlying tree client is cached
/// per `(db_path, account_uuid)` so later VAN witness calls can reuse the synced
/// in-memory tree state.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails or tree sync against
/// `node_url` fails for `round_id`.
Future<int> syncVoteTree({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required String nodeUrl,
}) => RustLib.instance.api.crateApiVotingSyncVoteTree(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  nodeUrl: nodeUrl,
);

/// Generate a Vote Authority Note Merkle witness for a delegation bundle.
///
/// `anchor_height` is the vote-tree height where the witness should be anchored;
/// callers must sync the same round before requesting the witness.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, `bundle_index` is out of
/// range for the round, or witness generation fails.
Future<VanWitness> generateVanWitness({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int anchorHeight,
}) => RustLib.instance.api.crateApiVotingGenerateVanWitness(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  anchorHeight: anchorHeight,
);

/// Clear process-local vote-tree sync state for a wallet or round.
///
/// Passing a non-empty round ID clears only that round's cached vote-tree sync
/// state by calling `zcash_voting::precompute::reset_vote_tree(db, round_id)`.
/// Passing `None` or an empty round ID performs account-wide vote-tree cleanup
/// with `zcash_voting::precompute::reset_vote_tree(db, "")`.
///
/// This does not clear unsigned delegation setup fields, delete durable recovery
/// rows, or abort in-flight proof/vote work already running on worker threads.
Future<void> resetVoteTree({
  required String dbPath,
  required String accountUuid,
  String? roundId,
}) => RustLib.instance.api.crateApiVotingResetVoteTree(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Clear process-local voting session state for a wallet or round.
///
/// Passing a non-empty round ID clears only that round's cached vote-tree sync
/// state and unsigned delegation setup fields by calling
/// `zcash_voting::precompute::reset_voting_session_state(db, round_id)`.
/// Passing `None` or an empty round ID performs account-wide vote-tree cleanup
/// with `zcash_voting::precompute::reset_voting_session_state(db, "")`.
///
/// This does not delete durable recovery rows or abort in-flight proof/vote
/// work already running on worker threads.
Future<void> resetVotingSessionState({
  required String dbPath,
  required String accountUuid,
  String? roundId,
}) => RustLib.instance.api.crateApiVotingResetVotingSessionState(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Delete all durable voting sidecar rows for an account.
///
/// This removes every persisted round scoped to `account_uuid`, relying on the
/// `zcash_voting` round deletion cascade for bundles, recovery rows, share
/// history, ballot intent, and cached tree state. Use this only at account
/// deletion boundaries, not for ordinary voting-session retries.
Future<int> deleteVotingAccountState({
  required String dbPath,
  required String accountUuid,
}) => RustLib.instance.api.crateApiVotingDeleteVotingAccountState(
  dbPath: dbPath,
  accountUuid: accountUuid,
);

/// Lists account/round pairs with durable unconfirmed helper shares.
///
/// The opaque session JSON is returned for caller-owned deadline checks. The
/// sidecar is not created when the wallet has never persisted voting state.
Future<List<ApiPendingShareRound>> listPendingShareRounds({
  required String dbPath,
  required List<String> accountUuids,
}) => RustLib.instance.api.crateApiVotingListPendingShareRounds(
  dbPath: dbPath,
  accountUuids: accountUuids,
);

/// Recover a committed but unsubmitted vote from persisted local recovery data.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, no matching commitment is
/// recoverable, or wire conversion fails.
Future<SignedVoteCommitmentsView> recoverVoteCommitment({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
}) => RustLib.instance.api.crateApiVotingRecoverVoteCommitment(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
);

/// Streaming variant of `build_vote_commitments`.
///
/// Emits per-proposal progress events, then a terminal `"result"` event carrying
/// `SignedVoteCommitmentsView`.
Stream<ApiVoteCommitEvent> buildVoteCommitmentsWithProgress({
  required String dbPath,
  required String accountUuid,
  required String network,
  required String roundId,
  required int bundleIndex,
  required List<int> storedHotkeySecret,
  required VanWitness vanWitness,
  required List<DraftVote> draftVotes,
}) => RustLib.instance.api.crateApiVotingBuildVoteCommitmentsWithProgress(
  dbPath: dbPath,
  accountUuid: accountUuid,
  network: network,
  roundId: roundId,
  bundleIndex: bundleIndex,
  storedHotkeySecret: storedHotkeySecret,
  vanWitness: vanWitness,
  draftVotes: draftVotes,
);

/// Load the full recovery/share-tracking summary for one voting round.
Future<RoundRecoveryStateView> getRoundRecoveryState({
  required String dbPath,
  required String accountUuid,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetRoundRecoveryState(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Record a submitted cast-vote transaction hash for one bundle/proposal key.
///
/// Repeated calls are idempotent only for the same transaction hash.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the vote key is missing, or
/// the stored hash conflicts with `tx_hash`.
Future<void> markVoteSubmitted({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required String txHash,
}) => RustLib.instance.api.crateApiVotingMarkVoteSubmitted(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  txHash: txHash,
);

/// Parse tx events and record a confirmed vote submission.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the event payload does not
/// match the expected round/type shape, or confirmation state cannot be stored.
Future<VoteConfirmation> confirmVoteSubmission({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required String txHash,
  required String eventsJson,
}) => RustLib.instance.api.crateApiVotingConfirmVoteSubmission(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  txHash: txHash,
  eventsJson: eventsJson,
);

/// Record helper-server submission state for one encrypted vote share.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the vote cannot be
/// recovered, or the share record cannot be persisted.
Future<void> recordShareDelegation({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required int shareIndex,
  required List<String> sentToUrls,
  required BigInt submitAt,
}) => RustLib.instance.api.crateApiVotingRecordShareDelegation(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  shareIndex: shareIndex,
  sentToUrls: sentToUrls,
  submitAt: submitAt,
);

/// Mark one delegated share as confirmed on-chain.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the vote cannot be
/// recovered, or share confirmation cannot be persisted.
Future<void> markShareConfirmed({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required int shareIndex,
}) => RustLib.instance.api.crateApiVotingMarkShareConfirmed(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  shareIndex: shareIndex,
);

/// Merge additional helper-server URLs into one share delegation record.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails or the share record cannot
/// be updated.
Future<void> addSentServers({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required int shareIndex,
  required List<String> newUrls,
}) => RustLib.instance.api.crateApiVotingAddSentServers(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  shareIndex: shareIndex,
  newUrls: newUrls,
);

/// Clear vote/delegation recovery columns and share-tracking rows for a round.
///
/// This is an explicit reset for finalized or abandoned rounds, not a normal
/// retry step.
Future<void> clearRecoveryState({
  required String dbPath,
  required String accountUuid,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingClearRecoveryState(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Compute the resumable voting-session plan for a round. The plan reports the
/// ordered remaining work (`next_steps`) and which proposals are still open.
Future<RoundPlanView> getRoundPlan({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required List<int> proposalIds,
}) => RustLib.instance.api.crateApiVotingGetRoundPlan(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  proposalIds: proposalIds,
);

/// Persist (insert or replace) the voter's ballot intent for one proposal.
/// Pass `skipped: true` for `Decision::Skipped`; otherwise `choice` must be set.
/// `num_options` is the proposal's declared option count.
Future<void> setBallotIntent({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int proposalId,
  required int numOptions,
  required bool skipped,
  int? choice,
}) => RustLib.instance.api.crateApiVotingSetBallotIntent(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  proposalId: proposalId,
  numOptions: numOptions,
  skipped: skipped,
  choice: choice,
);

/// Authenticate the static voting config bytes and surface the dynamic mirrors.
///
/// The wallet fetches the static trust anchor with its own transport and passes
/// the bytes here. Rust verifies the hash pin and decodes the static config,
/// returning the ordered `dynamic_config_urls` the wallet must walk before
/// calling [`resolve_voting_config_from_attempts`].
///
/// The returned list is always non-empty. A v1 static config names exactly one
/// URL and yields a single entry, so the v1 path is unchanged; a v2 config
/// yields its full mirror list, canonical origin first. Config errors are
/// returned as a flat string.
Future<List<String>> resolveStaticVotingConfig({
  required String source,
  required List<int> staticBytes,
}) => RustLib.instance.api.crateApiVotingResolveStaticVotingConfig(
  source: source,
  staticBytes: staticBytes,
);

/// Resolve and authenticate voting config from wallet-fetched bytes.
///
/// The wallet owns transport: it fetches the static bytes, calls
/// [`resolve_static_voting_config`] to learn the dynamic mirrors, fetches them
/// in order, and passes the accumulated per-mirror outcomes here. Rust picks the
/// first mirror that both decodes and authenticates, reports the ones it passed
/// over, and computes the config-switch classification against `previous`.
///
/// Callers are expected to re-invoke this after each mirror fetch rather than
/// gathering every mirror up front, so a healthy primary costs one request. A
/// mirror that resolves but authenticates no rounds is deprioritized rather than
/// skipped, so the caller should keep walking while `authenticated_rounds` is
/// empty and accept the round-less resolution only once the list is exhausted.
///
/// Config errors are returned as a flat string; transport failures never reach
/// this layer, they arrive as failed attempts.
Future<VotingConfigResolution> resolveVotingConfigFromAttempts({
  required String source,
  required List<int> staticBytes,
  required List<ApiDynamicConfigAttempt> attempts,
  ResolvedVotingConfig? previous,
}) => RustLib.instance.api.crateApiVotingResolveVotingConfigFromAttempts(
  source: source,
  staticBytes: staticBytes,
  attempts: attempts,
  previous: previous,
);

/// Round-scoped progress emitted while preparing, proving, and signing bundles.
///
/// Per-bundle events carry `bundle_index`. A terminal `"result"` event carries
/// the complete requested payload list in stable bundle-index order.
class ApiDelegationRoundEvent {
  final String phase;
  final int? bundleIndex;
  final double? proofProgress;
  final List<SignedDelegationPayloadView>? signedDelegationPayloads;

  const ApiDelegationRoundEvent({
    required this.phase,
    this.bundleIndex,
    this.proofProgress,
    this.signedDelegationPayloads,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      bundleIndex.hashCode ^
      proofProgress.hashCode ^
      signedDelegationPayloads.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDelegationRoundEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          bundleIndex == other.bundleIndex &&
          proofProgress == other.proofProgress &&
          signedDelegationPayloads == other.signedDelegationPayloads;
}

/// One externally produced delegation signature to prove and assemble.
class ApiDelegationSignatureInput {
  final int bundleIndex;
  final Uint8List sig;
  final Uint8List sighash;

  const ApiDelegationSignatureInput({
    required this.bundleIndex,
    required this.sig,
    required this.sighash,
  });

  @override
  int get hashCode => bundleIndex.hashCode ^ sig.hashCode ^ sighash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDelegationSignatureInput &&
          runtimeType == other.runtimeType &&
          bundleIndex == other.bundleIndex &&
          sig == other.sig &&
          sighash == other.sighash;
}

/// Durable hotkey-free delegation snapshot preparation result.
class ApiDelegationSnapshotPreparationResult {
  final bool complete;
  final bool alreadyComplete;
  final int bundleCount;
  final int noteCount;
  final BigInt eligibleWeight;
  final int witnessCount;
  final int pirProofCount;
  final int witnessesCached;
  final int witnessesGenerated;
  final int pirCached;
  final int pirFetched;

  const ApiDelegationSnapshotPreparationResult({
    required this.complete,
    required this.alreadyComplete,
    required this.bundleCount,
    required this.noteCount,
    required this.eligibleWeight,
    required this.witnessCount,
    required this.pirProofCount,
    required this.witnessesCached,
    required this.witnessesGenerated,
    required this.pirCached,
    required this.pirFetched,
  });

  @override
  int get hashCode =>
      complete.hashCode ^
      alreadyComplete.hashCode ^
      bundleCount.hashCode ^
      noteCount.hashCode ^
      eligibleWeight.hashCode ^
      witnessCount.hashCode ^
      pirProofCount.hashCode ^
      witnessesCached.hashCode ^
      witnessesGenerated.hashCode ^
      pirCached.hashCode ^
      pirFetched.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDelegationSnapshotPreparationResult &&
          runtimeType == other.runtimeType &&
          complete == other.complete &&
          alreadyComplete == other.alreadyComplete &&
          bundleCount == other.bundleCount &&
          noteCount == other.noteCount &&
          eligibleWeight == other.eligibleWeight &&
          witnessCount == other.witnessCount &&
          pirProofCount == other.pirProofCount &&
          witnessesCached == other.witnessesCached &&
          witnessesGenerated == other.witnessesGenerated &&
          pirCached == other.pirCached &&
          pirFetched == other.pirFetched;
}

class ApiDelegationSnapshotStatus {
  final bool complete;
  final int bundleCount;
  final int noteCount;
  final int witnessCount;
  final int pirProofCount;

  const ApiDelegationSnapshotStatus({
    required this.complete,
    required this.bundleCount,
    required this.noteCount,
    required this.witnessCount,
    required this.pirProofCount,
  });

  @override
  int get hashCode =>
      complete.hashCode ^
      bundleCount.hashCode ^
      noteCount.hashCode ^
      witnessCount.hashCode ^
      pirProofCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDelegationSnapshotStatus &&
          runtimeType == other.runtimeType &&
          complete == other.complete &&
          bundleCount == other.bundleCount &&
          noteCount == other.noteCount &&
          witnessCount == other.witnessCount &&
          pirProofCount == other.pirProofCount;
}

/// One wallet-side fetch outcome for a single dynamic config mirror.
///
/// Flat by necessity: the crate's [`DynamicConfigAttempt`] carries a
/// `Result<Vec<u8>, String>`, which flutter_rust_bridge cannot represent as a
/// struct field. Exactly one of `bytes` / `error` is expected to be set;
/// `bytes: None` means this mirror did not produce usable bytes and `error`
/// explains why for logging and diagnostics.
class ApiDynamicConfigAttempt {
  final String url;
  final Uint8List? bytes;
  final String? error;

  const ApiDynamicConfigAttempt({required this.url, this.bytes, this.error});

  @override
  int get hashCode => url.hashCode ^ bytes.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDynamicConfigAttempt &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          bytes == other.bytes &&
          error == other.error;
}

/// A dynamic config mirror the resolver passed over, and why.
class ApiDynamicConfigMirrorFailure {
  final String url;
  final String reason;

  const ApiDynamicConfigMirrorFailure({
    required this.url,
    required this.reason,
  });

  @override
  int get hashCode => url.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDynamicConfigMirrorFailure &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          reason == other.reason;
}

/// Outcome of an idempotent Keystone signature batch write.
class ApiKeystoneSignatureBatchResult {
  final int inserted;
  final int alreadyPresent;

  const ApiKeystoneSignatureBatchResult({
    required this.inserted,
    required this.alreadyPresent,
  });

  @override
  int get hashCode => inserted.hashCode ^ alreadyPresent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiKeystoneSignatureBatchResult &&
          runtimeType == other.runtimeType &&
          inserted == other.inserted &&
          alreadyPresent == other.alreadyPresent;
}

/// One Keystone delegation signature tuple to persist atomically.
class ApiKeystoneSignatureInput {
  final int bundleIndex;
  final Uint8List sig;
  final Uint8List sighash;
  final Uint8List rk;

  const ApiKeystoneSignatureInput({
    required this.bundleIndex,
    required this.sig,
    required this.sighash,
    required this.rk,
  });

  @override
  int get hashCode =>
      bundleIndex.hashCode ^ sig.hashCode ^ sighash.hashCode ^ rk.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiKeystoneSignatureInput &&
          runtimeType == other.runtimeType &&
          bundleIndex == other.bundleIndex &&
          sig == other.sig &&
          sighash == other.sighash &&
          rk == other.rk;
}

/// One account and round with durable unconfirmed helper shares.
class ApiPendingShareRound {
  final String accountUuid;
  final String roundId;
  final String? sessionJson;

  const ApiPendingShareRound({
    required this.accountUuid,
    required this.roundId,
    this.sessionJson,
  });

  @override
  int get hashCode =>
      accountUuid.hashCode ^ roundId.hashCode ^ sessionJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPendingShareRound &&
          runtimeType == other.runtimeType &&
          accountUuid == other.accountUuid &&
          roundId == other.roundId &&
          sessionJson == other.sessionJson;
}

/// FRB-facing outcome of the bundle-independent PIR proof cache warm-up.
class ApiPirCacheWarmupResult {
  /// Eligible notes selected at the snapshot height.
  final int noteCount;

  /// Nullifiers that already had a cached proof under the served root.
  final int cachedCount;

  /// Proofs fetched from the PIR server during this warm-up.
  final int fetchedCount;

  /// IMT root the PIR server served, as 32 little-endian bytes. Compare with
  /// the round's `nullifier_imt_root` to detect a stale snapshot.
  final Uint8List servedRoot;

  /// Cache rows evicted by automatic recency prune. Always `0` on this
  /// crate pin: `precompute_pir_proofs` prunes internally and does not
  /// report a count.
  final int prunedCount;

  const ApiPirCacheWarmupResult({
    required this.noteCount,
    required this.cachedCount,
    required this.fetchedCount,
    required this.servedRoot,
    required this.prunedCount,
  });

  @override
  int get hashCode =>
      noteCount.hashCode ^
      cachedCount.hashCode ^
      fetchedCount.hashCode ^
      servedRoot.hashCode ^
      prunedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPirCacheWarmupResult &&
          runtimeType == other.runtimeType &&
          noteCount == other.noteCount &&
          cachedCount == other.cachedCount &&
          fetchedCount == other.fetchedCount &&
          servedRoot == other.servedRoot &&
          prunedCount == other.prunedCount;
}

/// Progress event emitted while building ZKP2 vote commitments.
///
/// A terminal `"result"` event carries the completed commitment set; earlier
/// phase events include the active `(proposal_id, bundle_index)` pair.
class ApiVoteCommitEvent {
  final String phase;
  final int? proposalId;
  final int? bundleIndex;
  final double? proofProgress;
  final SignedVoteCommitmentsView? commitments;

  const ApiVoteCommitEvent({
    required this.phase,
    this.proposalId,
    this.bundleIndex,
    this.proofProgress,
    this.commitments,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      proposalId.hashCode ^
      bundleIndex.hashCode ^
      proofProgress.hashCode ^
      commitments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVoteCommitEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          proposalId == other.proposalId &&
          bundleIndex == other.bundleIndex &&
          proofProgress == other.proofProgress &&
          commitments == other.commitments;
}

/// Read-only minimum voting eligibility status for one round/account.
class ApiVotingEligibility {
  final bool isEligible;
  final int distinctNoteCount;
  final BigInt eligibleWeightZatoshi;

  /// Raw note value the privacy trim withholds from this round, not its
  /// bundle-quantized voting weight. Zero when nothing was withheld.
  final BigInt privacyTrimDroppedValueZatoshi;

  const ApiVotingEligibility({
    required this.isEligible,
    required this.distinctNoteCount,
    required this.eligibleWeightZatoshi,
    required this.privacyTrimDroppedValueZatoshi,
  });

  @override
  int get hashCode =>
      isEligible.hashCode ^
      distinctNoteCount.hashCode ^
      eligibleWeightZatoshi.hashCode ^
      privacyTrimDroppedValueZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingEligibility &&
          runtimeType == other.runtimeType &&
          isEligible == other.isEligible &&
          distinctNoteCount == other.distinctNoteCount &&
          eligibleWeightZatoshi == other.eligibleWeightZatoshi &&
          privacyTrimDroppedValueZatoshi ==
              other.privacyTrimDroppedValueZatoshi;
}

/// Shared delegation/voting round context passed across the FRB boundary.
///
/// This bundles the reusable round and wallet scope required by delegation setup,
/// proving, and keystone request flows.
class ApiVotingRoundContext {
  final String dbPath;
  final String lightwalletdUrl;
  final String network;
  final VotingRoundParams roundParams;
  final String roundName;
  final String? sessionJson;
  final String accountUuid;
  final int? maxRealNotesPerBundle;

  /// Authenticated PIR geometry expected from the selected endpoint.
  final PirLayout pirLayout;

  const ApiVotingRoundContext({
    required this.dbPath,
    required this.lightwalletdUrl,
    required this.network,
    required this.roundParams,
    required this.roundName,
    this.sessionJson,
    required this.accountUuid,
    this.maxRealNotesPerBundle,
    required this.pirLayout,
  });

  @override
  int get hashCode =>
      dbPath.hashCode ^
      lightwalletdUrl.hashCode ^
      network.hashCode ^
      roundParams.hashCode ^
      roundName.hashCode ^
      sessionJson.hashCode ^
      accountUuid.hashCode ^
      maxRealNotesPerBundle.hashCode ^
      pirLayout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingRoundContext &&
          runtimeType == other.runtimeType &&
          dbPath == other.dbPath &&
          lightwalletdUrl == other.lightwalletdUrl &&
          network == other.network &&
          roundParams == other.roundParams &&
          roundName == other.roundName &&
          sessionJson == other.sessionJson &&
          accountUuid == other.accountUuid &&
          maxRealNotesPerBundle == other.maxRealNotesPerBundle &&
          pirLayout == other.pirLayout;
}

class VotingConfigResolution {
  final ResolvedVotingConfig config;
  final ConfigSwitchKind switchKind;

  /// Mirrors skipped before the one that resolved. Empty on the happy path.
  final List<ApiDynamicConfigMirrorFailure> skippedMirrors;

  const VotingConfigResolution({
    required this.config,
    required this.switchKind,
    required this.skippedMirrors,
  });

  @override
  int get hashCode =>
      config.hashCode ^ switchKind.hashCode ^ skippedMirrors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VotingConfigResolution &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          switchKind == other.switchKind &&
          skippedMirrors == other.skippedMirrors;
}
