#!/usr/bin/env bash

if [[ -n "${ZSH_VERSION:-}" ]]; then
  # shellcheck disable=SC2296 # zsh current-file expansion.
  LARGE_VALUE_ENV_SOURCE="${(%):-%N}"
else
  LARGE_VALUE_ENV_SOURCE="${BASH_SOURCE[0]}"
fi
LARGE_VALUE_ROOT_DIR="$(cd "$(dirname "$LARGE_VALUE_ENV_SOURCE")/../.." && pwd)"

export IRONWOOD_COMPOSE_PROJECT_NAME="vizor-ironwood-large-value-regtest"
export IRONWOOD_STATE_DIR="${IRONWOOD_LARGE_VALUE_STATE_DIR:-$LARGE_VALUE_ROOT_DIR/.ironwood-large-value-regtest}"
export IRONWOOD_SNAPSHOT_DIR="${IRONWOOD_LARGE_VALUE_SNAPSHOT_DIR:-$LARGE_VALUE_ROOT_DIR/.ironwood-large-value-regtest-snapshots}"
export IRONWOOD_ZCASHD_IMAGE="${IRONWOOD_LARGE_VALUE_ZCASHD_IMAGE:-vizor-zero-zcashd-ironwood-large-value:v15-grant-1100000}"
export IRONWOOD_ZCASHD_RPC_PORT="${IRONWOOD_LARGE_VALUE_ZCASHD_RPC_PORT:-19234}"
export IRONWOOD_LIGHTWALLETD_PORT="${IRONWOOD_LARGE_VALUE_LIGHTWALLETD_PORT:-19069}"
export IRONWOOD_ACTIVATION_HEIGHT="${IRONWOOD_LARGE_VALUE_ACTIVATION_HEIGHT:-500}"

export E2E_DRIVER_PORT="${IRONWOOD_LARGE_VALUE_DRIVER_PORT:-39085}"
export E2E_LIGHTWALLETD_URL="http://127.0.0.1:$IRONWOOD_LIGHTWALLETD_PORT"
